// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: conf.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 优先级
type Priority int32

const (
	Priority_Low    Priority = 0
	Priority_Medium Priority = 1
	Priority_High   Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "Low",
		1: "Medium",
		2: "High",
	}
	Priority_value = map[string]int32{
		"Low":    0,
		"Medium": 1,
		"High":   2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_conf_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

type AppConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 必传，接口QPS限流值，首次请求时初始化限流器，修改qps重启服务生效
	Qps uint32 `protobuf:"varint,1,opt,name=qps,proto3" json:"qps,omitempty"`
	// 必传
	AccessToken   string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConf) Reset() {
	*x = AppConf{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConf) ProtoMessage() {}

func (x *AppConf) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConf.ProtoReflect.Descriptor instead.
func (*AppConf) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *AppConf) GetQps() uint32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *AppConf) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type Conf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 必传，本次请求的优先级
	Priority Priority `protobuf:"varint,1,opt,name=priority,proto3,enum=conf.Priority" json:"priority,omitempty"`
	// map的key为应用唯一标识，该map长度大于1时，多应用会自动负载均衡
	AccessTokenMap map[uint32]*AppConf `protobuf:"bytes,2,rep,name=access_token_map,json=accessTokenMap,proto3" json:"access_token_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 高优先级队列长度，默认999,注意当队列满时再次请求会报错
	HighPriorityLen uint32 `protobuf:"varint,3,opt,name=high_priority_len,json=highPriorityLen,proto3" json:"high_priority_len,omitempty"`
	// 中优先级队列长度，默认3999,注意当队列满时再次请求会报错
	MediumPriorityLen uint32 `protobuf:"varint,4,opt,name=medium_priority_len,json=mediumPriorityLen,proto3" json:"medium_priority_len,omitempty"`
	// 低优先级队列长度，默认9999,注意当队列满时再次请求会报错
	LowPriorityLen uint32 `protobuf:"varint,5,opt,name=low_priority_len,json=lowPriorityLen,proto3" json:"low_priority_len,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conf) Reset() {
	*x = Conf{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conf) ProtoMessage() {}

func (x *Conf) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conf.ProtoReflect.Descriptor instead.
func (*Conf) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Conf) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_Low
}

func (x *Conf) GetAccessTokenMap() map[uint32]*AppConf {
	if x != nil {
		return x.AccessTokenMap
	}
	return nil
}

func (x *Conf) GetHighPriorityLen() uint32 {
	if x != nil {
		return x.HighPriorityLen
	}
	return 0
}

func (x *Conf) GetMediumPriorityLen() uint32 {
	if x != nil {
		return x.MediumPriorityLen
	}
	return 0
}

func (x *Conf) GetLowPriorityLen() uint32 {
	if x != nil {
		return x.LowPriorityLen
	}
	return 0
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\x04conf\">\n" +
	"\aAppConf\x12\x10\n" +
	"\x03qps\x18\x01 \x01(\rR\x03qps\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"\xd4\x02\n" +
	"\x04Conf\x12*\n" +
	"\bpriority\x18\x01 \x01(\x0e2\x0e.conf.PriorityR\bpriority\x12H\n" +
	"\x10access_token_map\x18\x02 \x03(\v2\x1e.conf.Conf.AccessTokenMapEntryR\x0eaccessTokenMap\x12*\n" +
	"\x11high_priority_len\x18\x03 \x01(\rR\x0fhighPriorityLen\x12.\n" +
	"\x13medium_priority_len\x18\x04 \x01(\rR\x11mediumPriorityLen\x12(\n" +
	"\x10low_priority_len\x18\x05 \x01(\rR\x0elowPriorityLen\x1aP\n" +
	"\x13AccessTokenMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.conf.AppConfR\x05value:\x028\x01*)\n" +
	"\bPriority\x12\a\n" +
	"\x03Low\x10\x00\x12\n" +
	"\n" +
	"\x06Medium\x10\x01\x12\b\n" +
	"\x04High\x10\x02B-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_conf_proto_goTypes = []any{
	(Priority)(0),   // 0: conf.Priority
	(*AppConf)(nil), // 1: conf.AppConf
	(*Conf)(nil),    // 2: conf.Conf
	nil,             // 3: conf.Conf.AccessTokenMapEntry
}
var file_conf_proto_depIdxs = []int32{
	0, // 0: conf.Conf.priority:type_name -> conf.Priority
	3, // 1: conf.Conf.access_token_map:type_name -> conf.Conf.AccessTokenMapEntry
	1, // 2: conf.Conf.AccessTokenMapEntry.value:type_name -> conf.AppConf
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		EnumInfos:         file_conf_proto_enumTypes,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
