// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: material.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoCoverSuggestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestList) Reset() {
	*x = VideoCoverSuggestList{}
	mi := &file_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestList) ProtoMessage() {}

func (x *VideoCoverSuggestList) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestList.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestList) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{0}
}

func (x *VideoCoverSuggestList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoCoverSuggestList) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoCoverSuggestList) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoCoverSuggestList) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type VideoCoverSuggestData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List          []*VideoCoverSuggestList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestData) Reset() {
	*x = VideoCoverSuggestData{}
	mi := &file_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestData) ProtoMessage() {}

func (x *VideoCoverSuggestData) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestData.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestData) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{1}
}

func (x *VideoCoverSuggestData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoCoverSuggestData) GetList() []*VideoCoverSuggestList {
	if x != nil {
		return x.List
	}
	return nil
}

type VideoCoverSuggestReq struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Conf          *Conf                       `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *VideoCoverSuggestReqParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestReq) Reset() {
	*x = VideoCoverSuggestReq{}
	mi := &file_material_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestReq) ProtoMessage() {}

func (x *VideoCoverSuggestReq) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestReq.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestReq) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{2}
}

func (x *VideoCoverSuggestReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *VideoCoverSuggestReq) GetParams() *VideoCoverSuggestReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type VideoCoverSuggestReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  uint64                 `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestReqParams) Reset() {
	*x = VideoCoverSuggestReqParams{}
	mi := &file_material_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestReqParams) ProtoMessage() {}

func (x *VideoCoverSuggestReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestReqParams.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestReqParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{3}
}

func (x *VideoCoverSuggestReqParams) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *VideoCoverSuggestReqParams) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type VideoCoverSuggestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *VideoCoverSuggestData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestResp) Reset() {
	*x = VideoCoverSuggestResp{}
	mi := &file_material_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestResp) ProtoMessage() {}

func (x *VideoCoverSuggestResp) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestResp.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestResp) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{4}
}

func (x *VideoCoverSuggestResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VideoCoverSuggestResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VideoCoverSuggestResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VideoCoverSuggestResp) GetData() *VideoCoverSuggestData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_material_proto protoreflect.FileDescriptor

const file_material_proto_rawDesc = "" +
	"\n" +
	"\x0ematerial.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"g\n" +
	"\x15VideoCoverSuggestList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"a\n" +
	"\x15VideoCoverSuggestData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x120\n" +
	"\x04list\x18\x02 \x03(\v2\x1c.ocean.VideoCoverSuggestListR\x04list\"q\n" +
	"\x14VideoCoverSuggestReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x129\n" +
	"\x06params\x18\x02 \x01(\v2!.ocean.VideoCoverSuggestReqParamsR\x06params\"\\\n" +
	"\x1aVideoCoverSuggestReqParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x04R\fadvertiserId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"\x96\x01\n" +
	"\x15VideoCoverSuggestResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x120\n" +
	"\x04data\x18\x04 \x01(\v2\x1c.ocean.VideoCoverSuggestDataR\x04dataB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_material_proto_rawDescOnce sync.Once
	file_material_proto_rawDescData []byte
)

func file_material_proto_rawDescGZIP() []byte {
	file_material_proto_rawDescOnce.Do(func() {
		file_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_material_proto_rawDesc), len(file_material_proto_rawDesc)))
	})
	return file_material_proto_rawDescData
}

var file_material_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_material_proto_goTypes = []any{
	(*VideoCoverSuggestList)(nil),      // 0: ocean.VideoCoverSuggestList
	(*VideoCoverSuggestData)(nil),      // 1: ocean.VideoCoverSuggestData
	(*VideoCoverSuggestReq)(nil),       // 2: ocean.VideoCoverSuggestReq
	(*VideoCoverSuggestReqParams)(nil), // 3: ocean.VideoCoverSuggestReqParams
	(*VideoCoverSuggestResp)(nil),      // 4: ocean.VideoCoverSuggestResp
	(*Conf)(nil),                       // 5: conf.Conf
}
var file_material_proto_depIdxs = []int32{
	0, // 0: ocean.VideoCoverSuggestData.list:type_name -> ocean.VideoCoverSuggestList
	5, // 1: ocean.VideoCoverSuggestReq.conf:type_name -> conf.Conf
	3, // 2: ocean.VideoCoverSuggestReq.params:type_name -> ocean.VideoCoverSuggestReqParams
	1, // 3: ocean.VideoCoverSuggestResp.data:type_name -> ocean.VideoCoverSuggestData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_material_proto_init() }
func file_material_proto_init() {
	if File_material_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_material_proto_rawDesc), len(file_material_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_material_proto_goTypes,
		DependencyIndexes: file_material_proto_depIdxs,
		MessageInfos:      file_material_proto_msgTypes,
	}.Build()
	File_material_proto = out.File
	file_material_proto_goTypes = nil
	file_material_proto_depIdxs = nil
}
