// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: material.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoCoverSuggestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestList) Reset() {
	*x = VideoCoverSuggestList{}
	mi := &file_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestList) ProtoMessage() {}

func (x *VideoCoverSuggestList) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestList.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestList) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{0}
}

func (x *VideoCoverSuggestList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoCoverSuggestList) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoCoverSuggestList) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoCoverSuggestList) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type VideoCoverSuggestData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List          []*VideoCoverSuggestList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestData) Reset() {
	*x = VideoCoverSuggestData{}
	mi := &file_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestData) ProtoMessage() {}

func (x *VideoCoverSuggestData) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestData.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestData) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{1}
}

func (x *VideoCoverSuggestData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoCoverSuggestData) GetList() []*VideoCoverSuggestList {
	if x != nil {
		return x.List
	}
	return nil
}

type VideoCoverSuggestReq struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Conf          *Conf                       `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *VideoCoverSuggestReqParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestReq) Reset() {
	*x = VideoCoverSuggestReq{}
	mi := &file_material_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestReq) ProtoMessage() {}

func (x *VideoCoverSuggestReq) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestReq.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestReq) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{2}
}

func (x *VideoCoverSuggestReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *VideoCoverSuggestReq) GetParams() *VideoCoverSuggestReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type VideoCoverSuggestReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  uint64                 `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestReqParams) Reset() {
	*x = VideoCoverSuggestReqParams{}
	mi := &file_material_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestReqParams) ProtoMessage() {}

func (x *VideoCoverSuggestReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestReqParams.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestReqParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{3}
}

func (x *VideoCoverSuggestReqParams) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *VideoCoverSuggestReqParams) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type VideoCoverSuggestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *VideoCoverSuggestData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCoverSuggestResp) Reset() {
	*x = VideoCoverSuggestResp{}
	mi := &file_material_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCoverSuggestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCoverSuggestResp) ProtoMessage() {}

func (x *VideoCoverSuggestResp) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCoverSuggestResp.ProtoReflect.Descriptor instead.
func (*VideoCoverSuggestResp) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{4}
}

func (x *VideoCoverSuggestResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VideoCoverSuggestResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VideoCoverSuggestResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VideoCoverSuggestResp) GetData() *VideoCoverSuggestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileImageAdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *FileImageAdReqParams  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileImageAdReq) Reset() {
	*x = FileImageAdReq{}
	mi := &file_material_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileImageAdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileImageAdReq) ProtoMessage() {}

func (x *FileImageAdReq) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileImageAdReq.ProtoReflect.Descriptor instead.
func (*FileImageAdReq) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{5}
}

func (x *FileImageAdReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *FileImageAdReq) GetParams() *FileImageAdReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type FileImageAdReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  uint64                 `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	IsAigc        bool                   `protobuf:"varint,4,opt,name=is_aigc,json=isAigc,proto3" json:"is_aigc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileImageAdReqParams) Reset() {
	*x = FileImageAdReqParams{}
	mi := &file_material_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileImageAdReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileImageAdReqParams) ProtoMessage() {}

func (x *FileImageAdReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileImageAdReqParams.ProtoReflect.Descriptor instead.
func (*FileImageAdReqParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{6}
}

func (x *FileImageAdReqParams) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *FileImageAdReqParams) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *FileImageAdReqParams) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileImageAdReqParams) GetIsAigc() bool {
	if x != nil {
		return x.IsAigc
	}
	return false
}

type FileImageAdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *FileImageAdData       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileImageAdResp) Reset() {
	*x = FileImageAdResp{}
	mi := &file_material_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileImageAdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileImageAdResp) ProtoMessage() {}

func (x *FileImageAdResp) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileImageAdResp.ProtoReflect.Descriptor instead.
func (*FileImageAdResp) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{7}
}

func (x *FileImageAdResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileImageAdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileImageAdResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileImageAdResp) GetData() *FileImageAdData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileImageAdData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	MaterialId    uint64                 `protobuf:"varint,8,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileImageAdData) Reset() {
	*x = FileImageAdData{}
	mi := &file_material_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileImageAdData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileImageAdData) ProtoMessage() {}

func (x *FileImageAdData) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileImageAdData.ProtoReflect.Descriptor instead.
func (*FileImageAdData) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{8}
}

func (x *FileImageAdData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileImageAdData) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileImageAdData) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FileImageAdData) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FileImageAdData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileImageAdData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FileImageAdData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FileImageAdData) GetMaterialId() uint64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type FileUploadTaskCreateReq struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Conf          *Conf                          `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *FileUploadTaskCreateReqParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskCreateReq) Reset() {
	*x = FileUploadTaskCreateReq{}
	mi := &file_material_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskCreateReq) ProtoMessage() {}

func (x *FileUploadTaskCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskCreateReq.ProtoReflect.Descriptor instead.
func (*FileUploadTaskCreateReq) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{9}
}

func (x *FileUploadTaskCreateReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *FileUploadTaskCreateReq) GetParams() *FileUploadTaskCreateReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type FileUploadTaskCreateReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Labels        []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	IsAigc        bool                   `protobuf:"varint,6,opt,name=is_aigc,json=isAigc,proto3" json:"is_aigc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskCreateReqParams) Reset() {
	*x = FileUploadTaskCreateReqParams{}
	mi := &file_material_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskCreateReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskCreateReqParams) ProtoMessage() {}

func (x *FileUploadTaskCreateReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskCreateReqParams.ProtoReflect.Descriptor instead.
func (*FileUploadTaskCreateReqParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{10}
}

func (x *FileUploadTaskCreateReqParams) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FileUploadTaskCreateReqParams) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FileUploadTaskCreateReqParams) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadTaskCreateReqParams) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *FileUploadTaskCreateReqParams) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *FileUploadTaskCreateReqParams) GetIsAigc() bool {
	if x != nil {
		return x.IsAigc
	}
	return false
}

type FileUploadTaskCreateResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          int32                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                    `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *FileUploadTaskCreateData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskCreateResp) Reset() {
	*x = FileUploadTaskCreateResp{}
	mi := &file_material_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskCreateResp) ProtoMessage() {}

func (x *FileUploadTaskCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskCreateResp.ProtoReflect.Descriptor instead.
func (*FileUploadTaskCreateResp) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{11}
}

func (x *FileUploadTaskCreateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileUploadTaskCreateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileUploadTaskCreateResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileUploadTaskCreateResp) GetData() *FileUploadTaskCreateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileUploadTaskCreateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskCreateData) Reset() {
	*x = FileUploadTaskCreateData{}
	mi := &file_material_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskCreateData) ProtoMessage() {}

func (x *FileUploadTaskCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskCreateData.ProtoReflect.Descriptor instead.
func (*FileUploadTaskCreateData) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{12}
}

func (x *FileUploadTaskCreateData) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type FileUploadTaskListReq struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Conf          *Conf                        `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *FileUploadTaskListReqParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskListReq) Reset() {
	*x = FileUploadTaskListReq{}
	mi := &file_material_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskListReq) ProtoMessage() {}

func (x *FileUploadTaskListReq) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskListReq.ProtoReflect.Descriptor instead.
func (*FileUploadTaskListReq) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{13}
}

func (x *FileUploadTaskListReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *FileUploadTaskListReq) GetParams() *FileUploadTaskListReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type FileUploadTaskListReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	TaskIds       []uint64               `protobuf:"varint,3,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskListReqParams) Reset() {
	*x = FileUploadTaskListReqParams{}
	mi := &file_material_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskListReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskListReqParams) ProtoMessage() {}

func (x *FileUploadTaskListReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskListReqParams.ProtoReflect.Descriptor instead.
func (*FileUploadTaskListReqParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{14}
}

func (x *FileUploadTaskListReqParams) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FileUploadTaskListReqParams) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FileUploadTaskListReqParams) GetTaskIds() []uint64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type FileUploadTaskListResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                  `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *FileUploadTaskListData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskListResp) Reset() {
	*x = FileUploadTaskListResp{}
	mi := &file_material_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskListResp) ProtoMessage() {}

func (x *FileUploadTaskListResp) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskListResp.ProtoReflect.Descriptor instead.
func (*FileUploadTaskListResp) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{15}
}

func (x *FileUploadTaskListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileUploadTaskListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileUploadTaskListResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileUploadTaskListResp) GetData() *FileUploadTaskListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileUploadTaskListData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	List          []*FileUploadTaskListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskListData) Reset() {
	*x = FileUploadTaskListData{}
	mi := &file_material_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskListData) ProtoMessage() {}

func (x *FileUploadTaskListData) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskListData.ProtoReflect.Descriptor instead.
func (*FileUploadTaskListData) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{16}
}

func (x *FileUploadTaskListData) GetList() []*FileUploadTaskListItem {
	if x != nil {
		return x.List
	}
	return nil
}

type FileUploadTaskListItem struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                           `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	TaskId        int64                            `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VideoInfo     *FileUploadTaskListItemVideoInfo `protobuf:"bytes,4,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskListItem) Reset() {
	*x = FileUploadTaskListItem{}
	mi := &file_material_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskListItem) ProtoMessage() {}

func (x *FileUploadTaskListItem) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskListItem.ProtoReflect.Descriptor instead.
func (*FileUploadTaskListItem) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{17}
}

func (x *FileUploadTaskListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileUploadTaskListItem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *FileUploadTaskListItem) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *FileUploadTaskListItem) GetVideoInfo() *FileUploadTaskListItemVideoInfo {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

type FileUploadTaskListItemVideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTaskListItemVideoInfo) Reset() {
	*x = FileUploadTaskListItemVideoInfo{}
	mi := &file_material_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTaskListItemVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTaskListItemVideoInfo) ProtoMessage() {}

func (x *FileUploadTaskListItemVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTaskListItemVideoInfo.ProtoReflect.Descriptor instead.
func (*FileUploadTaskListItemVideoInfo) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{18}
}

func (x *FileUploadTaskListItemVideoInfo) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *FileUploadTaskListItemVideoInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadTaskListItemVideoInfo) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *FileUploadTaskListItemVideoInfo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

var File_material_proto protoreflect.FileDescriptor

const file_material_proto_rawDesc = "" +
	"\n" +
	"\x0ematerial.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"g\n" +
	"\x15VideoCoverSuggestList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"a\n" +
	"\x15VideoCoverSuggestData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x120\n" +
	"\x04list\x18\x02 \x03(\v2\x1c.ocean.VideoCoverSuggestListR\x04list\"q\n" +
	"\x14VideoCoverSuggestReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x129\n" +
	"\x06params\x18\x02 \x01(\v2!.ocean.VideoCoverSuggestReqParamsR\x06params\"\\\n" +
	"\x1aVideoCoverSuggestReqParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x04R\fadvertiserId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"\x96\x01\n" +
	"\x15VideoCoverSuggestResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x120\n" +
	"\x04data\x18\x04 \x01(\v2\x1c.ocean.VideoCoverSuggestDataR\x04data\"e\n" +
	"\x0eFileImageAdReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x123\n" +
	"\x06params\x18\x02 \x01(\v2\x1b.ocean.FileImageAdReqParamsR\x06params\"\x8d\x01\n" +
	"\x14FileImageAdReqParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x04R\fadvertiserId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x17\n" +
	"\ais_aigc\x18\x04 \x01(\bR\x06isAigc\"\x8a\x01\n" +
	"\x0fFileImageAdResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12*\n" +
	"\x04data\x18\x04 \x01(\v2\x16.ocean.FileImageAdDataR\x04data\"\xcc\x01\n" +
	"\x0fFileImageAdData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12\x1f\n" +
	"\vmaterial_id\x18\b \x01(\x04R\n" +
	"materialId\"w\n" +
	"\x17FileUploadTaskCreateReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x12<\n" +
	"\x06params\x18\x02 \x01(\v2$.ocean.FileUploadTaskCreateReqParamsR\x06params\"\xcb\x01\n" +
	"\x1dFileUploadTaskCreateReqParams\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12\x17\n" +
	"\ais_aigc\x18\x06 \x01(\bR\x06isAigc\"\x9c\x01\n" +
	"\x18FileUploadTaskCreateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x123\n" +
	"\x04data\x18\x04 \x01(\v2\x1f.ocean.FileUploadTaskCreateDataR\x04data\"3\n" +
	"\x18FileUploadTaskCreateData\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"s\n" +
	"\x15FileUploadTaskListReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x12:\n" +
	"\x06params\x18\x02 \x01(\v2\".ocean.FileUploadTaskListReqParamsR\x06params\"z\n" +
	"\x1bFileUploadTaskListReqParams\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\x04R\ataskIds\"\x98\x01\n" +
	"\x16FileUploadTaskListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x121\n" +
	"\x04data\x18\x04 \x01(\v2\x1d.ocean.FileUploadTaskListDataR\x04data\"K\n" +
	"\x16FileUploadTaskListData\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.ocean.FileUploadTaskListItemR\x04list\"\xad\x01\n" +
	"\x16FileUploadTaskListItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12E\n" +
	"\n" +
	"video_info\x18\x04 \x01(\v2&.ocean.FileUploadTaskListItemVideoInfoR\tvideoInfo\"\x8e\x01\n" +
	"\x1fFileUploadTaskListItemVideoInfo\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrlB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_material_proto_rawDescOnce sync.Once
	file_material_proto_rawDescData []byte
)

func file_material_proto_rawDescGZIP() []byte {
	file_material_proto_rawDescOnce.Do(func() {
		file_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_material_proto_rawDesc), len(file_material_proto_rawDesc)))
	})
	return file_material_proto_rawDescData
}

var file_material_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_material_proto_goTypes = []any{
	(*VideoCoverSuggestList)(nil),           // 0: ocean.VideoCoverSuggestList
	(*VideoCoverSuggestData)(nil),           // 1: ocean.VideoCoverSuggestData
	(*VideoCoverSuggestReq)(nil),            // 2: ocean.VideoCoverSuggestReq
	(*VideoCoverSuggestReqParams)(nil),      // 3: ocean.VideoCoverSuggestReqParams
	(*VideoCoverSuggestResp)(nil),           // 4: ocean.VideoCoverSuggestResp
	(*FileImageAdReq)(nil),                  // 5: ocean.FileImageAdReq
	(*FileImageAdReqParams)(nil),            // 6: ocean.FileImageAdReqParams
	(*FileImageAdResp)(nil),                 // 7: ocean.FileImageAdResp
	(*FileImageAdData)(nil),                 // 8: ocean.FileImageAdData
	(*FileUploadTaskCreateReq)(nil),         // 9: ocean.FileUploadTaskCreateReq
	(*FileUploadTaskCreateReqParams)(nil),   // 10: ocean.FileUploadTaskCreateReqParams
	(*FileUploadTaskCreateResp)(nil),        // 11: ocean.FileUploadTaskCreateResp
	(*FileUploadTaskCreateData)(nil),        // 12: ocean.FileUploadTaskCreateData
	(*FileUploadTaskListReq)(nil),           // 13: ocean.FileUploadTaskListReq
	(*FileUploadTaskListReqParams)(nil),     // 14: ocean.FileUploadTaskListReqParams
	(*FileUploadTaskListResp)(nil),          // 15: ocean.FileUploadTaskListResp
	(*FileUploadTaskListData)(nil),          // 16: ocean.FileUploadTaskListData
	(*FileUploadTaskListItem)(nil),          // 17: ocean.FileUploadTaskListItem
	(*FileUploadTaskListItemVideoInfo)(nil), // 18: ocean.FileUploadTaskListItemVideoInfo
	(*Conf)(nil),                            // 19: conf.Conf
}
var file_material_proto_depIdxs = []int32{
	0,  // 0: ocean.VideoCoverSuggestData.list:type_name -> ocean.VideoCoverSuggestList
	19, // 1: ocean.VideoCoverSuggestReq.conf:type_name -> conf.Conf
	3,  // 2: ocean.VideoCoverSuggestReq.params:type_name -> ocean.VideoCoverSuggestReqParams
	1,  // 3: ocean.VideoCoverSuggestResp.data:type_name -> ocean.VideoCoverSuggestData
	19, // 4: ocean.FileImageAdReq.conf:type_name -> conf.Conf
	6,  // 5: ocean.FileImageAdReq.params:type_name -> ocean.FileImageAdReqParams
	8,  // 6: ocean.FileImageAdResp.data:type_name -> ocean.FileImageAdData
	19, // 7: ocean.FileUploadTaskCreateReq.conf:type_name -> conf.Conf
	10, // 8: ocean.FileUploadTaskCreateReq.params:type_name -> ocean.FileUploadTaskCreateReqParams
	12, // 9: ocean.FileUploadTaskCreateResp.data:type_name -> ocean.FileUploadTaskCreateData
	19, // 10: ocean.FileUploadTaskListReq.conf:type_name -> conf.Conf
	14, // 11: ocean.FileUploadTaskListReq.params:type_name -> ocean.FileUploadTaskListReqParams
	16, // 12: ocean.FileUploadTaskListResp.data:type_name -> ocean.FileUploadTaskListData
	17, // 13: ocean.FileUploadTaskListData.list:type_name -> ocean.FileUploadTaskListItem
	18, // 14: ocean.FileUploadTaskListItem.video_info:type_name -> ocean.FileUploadTaskListItemVideoInfo
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_material_proto_init() }
func file_material_proto_init() {
	if File_material_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_material_proto_rawDesc), len(file_material_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_material_proto_goTypes,
		DependencyIndexes: file_material_proto_depIdxs,
		MessageInfos:      file_material_proto_msgTypes,
	}.Build()
	File_material_proto = out.File
	file_material_proto_goTypes = nil
	file_material_proto_depIdxs = nil
}
