// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: ocean.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_QueueLen_FullMethodName          = "/ocean.Api/QueueLen"
	Api_Awemes_FullMethodName            = "/ocean.Api/Awemes"
	Api_VideoCoverSuggest_FullMethodName = "/ocean.Api/VideoCoverSuggest"
	Api_FileImageAd_FullMethodName       = "/ocean.Api/FileImageAd"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	QueueLen(ctx context.Context, in *QueueLenReq, opts ...grpc.CallOption) (*QueueLenResp, error)
	Awemes(ctx context.Context, in *AwemesReq, opts ...grpc.CallOption) (*AwemesResp, error)
	VideoCoverSuggest(ctx context.Context, in *VideoCoverSuggestReq, opts ...grpc.CallOption) (*VideoCoverSuggestResp, error)
	FileImageAd(ctx context.Context, in *FileImageAdReq, opts ...grpc.CallOption) (*FileImageAdResp, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) QueueLen(ctx context.Context, in *QueueLenReq, opts ...grpc.CallOption) (*QueueLenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueLenResp)
	err := c.cc.Invoke(ctx, Api_QueueLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Awemes(ctx context.Context, in *AwemesReq, opts ...grpc.CallOption) (*AwemesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwemesResp)
	err := c.cc.Invoke(ctx, Api_Awemes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) VideoCoverSuggest(ctx context.Context, in *VideoCoverSuggestReq, opts ...grpc.CallOption) (*VideoCoverSuggestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoCoverSuggestResp)
	err := c.cc.Invoke(ctx, Api_VideoCoverSuggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) FileImageAd(ctx context.Context, in *FileImageAdReq, opts ...grpc.CallOption) (*FileImageAdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileImageAdResp)
	err := c.cc.Invoke(ctx, Api_FileImageAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	QueueLen(context.Context, *QueueLenReq) (*QueueLenResp, error)
	Awemes(context.Context, *AwemesReq) (*AwemesResp, error)
	VideoCoverSuggest(context.Context, *VideoCoverSuggestReq) (*VideoCoverSuggestResp, error)
	FileImageAd(context.Context, *FileImageAdReq) (*FileImageAdResp, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) QueueLen(context.Context, *QueueLenReq) (*QueueLenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueLen not implemented")
}
func (UnimplementedApiServer) Awemes(context.Context, *AwemesReq) (*AwemesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Awemes not implemented")
}
func (UnimplementedApiServer) VideoCoverSuggest(context.Context, *VideoCoverSuggestReq) (*VideoCoverSuggestResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoCoverSuggest not implemented")
}
func (UnimplementedApiServer) FileImageAd(context.Context, *FileImageAdReq) (*FileImageAdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileImageAd not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_QueueLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueLenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).QueueLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_QueueLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).QueueLen(ctx, req.(*QueueLenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Awemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwemesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Awemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_Awemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Awemes(ctx, req.(*AwemesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_VideoCoverSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoCoverSuggestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).VideoCoverSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_VideoCoverSuggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).VideoCoverSuggest(ctx, req.(*VideoCoverSuggestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_FileImageAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileImageAdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).FileImageAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_FileImageAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).FileImageAd(ctx, req.(*FileImageAdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocean.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueLen",
			Handler:    _Api_QueueLen_Handler,
		},
		{
			MethodName: "Awemes",
			Handler:    _Api_Awemes_Handler,
		},
		{
			MethodName: "VideoCoverSuggest",
			Handler:    _Api_VideoCoverSuggest_Handler,
		},
		{
			MethodName: "FileImageAd",
			Handler:    _Api_FileImageAd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocean.proto",
}
