// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: ocean.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ocean_proto protoreflect.FileDescriptor

const file_ocean_proto_rawDesc = "" +
	"\n" +
	"\vocean.proto\x12\x05ocean\x1a\vtools.proto\x1a\fstatus.proto\x1a\x0ematerial.proto2\xf7\x01\n" +
	"\x03Api\x123\n" +
	"\bQueueLen\x12\x12.ocean.QueueLenReq\x1a\x13.ocean.QueueLenResp\x12-\n" +
	"\x06Awemes\x12\x10.ocean.AwemesReq\x1a\x11.ocean.AwemesResp\x12N\n" +
	"\x11VideoCoverSuggest\x12\x1b.ocean.VideoCoverSuggestReq\x1a\x1c.ocean.VideoCoverSuggestResp\x12<\n" +
	"\vFileImageAd\x12\x15.ocean.FileImageAdReq\x1a\x16.ocean.FileImageAdRespB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var file_ocean_proto_goTypes = []any{
	(*QueueLenReq)(nil),           // 0: ocean.QueueLenReq
	(*AwemesReq)(nil),             // 1: ocean.AwemesReq
	(*VideoCoverSuggestReq)(nil),  // 2: ocean.VideoCoverSuggestReq
	(*FileImageAdReq)(nil),        // 3: ocean.FileImageAdReq
	(*QueueLenResp)(nil),          // 4: ocean.QueueLenResp
	(*AwemesResp)(nil),            // 5: ocean.AwemesResp
	(*VideoCoverSuggestResp)(nil), // 6: ocean.VideoCoverSuggestResp
	(*FileImageAdResp)(nil),       // 7: ocean.FileImageAdResp
}
var file_ocean_proto_depIdxs = []int32{
	0, // 0: ocean.Api.QueueLen:input_type -> ocean.QueueLenReq
	1, // 1: ocean.Api.Awemes:input_type -> ocean.AwemesReq
	2, // 2: ocean.Api.VideoCoverSuggest:input_type -> ocean.VideoCoverSuggestReq
	3, // 3: ocean.Api.FileImageAd:input_type -> ocean.FileImageAdReq
	4, // 4: ocean.Api.QueueLen:output_type -> ocean.QueueLenResp
	5, // 5: ocean.Api.Awemes:output_type -> ocean.AwemesResp
	6, // 6: ocean.Api.VideoCoverSuggest:output_type -> ocean.VideoCoverSuggestResp
	7, // 7: ocean.Api.FileImageAd:output_type -> ocean.FileImageAdResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocean_proto_init() }
func file_ocean_proto_init() {
	if File_ocean_proto != nil {
		return
	}
	file_tools_proto_init()
	file_status_proto_init()
	file_material_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocean_proto_rawDesc), len(file_ocean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocean_proto_goTypes,
		DependencyIndexes: file_ocean_proto_depIdxs,
	}.Build()
	File_ocean_proto = out.File
	file_ocean_proto_goTypes = nil
	file_ocean_proto_depIdxs = nil
}
