// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: ocean.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ocean_proto protoreflect.FileDescriptor

const file_ocean_proto_rawDesc = "" +
	"\n" +
	"\vocean.proto\x12\x05ocean\x1a\vtools.proto\x1a\fstatus.proto\x1a\x0ematerial.proto\x1a\x0fpromotion.proto\x1a\rproject.proto\x1a\freport.proto2\xee\x05\n" +
	"\x03Api\x123\n" +
	"\bQueueLen\x12\x12.ocean.QueueLenReq\x1a\x13.ocean.QueueLenResp\x12-\n" +
	"\x06Awemes\x12\x10.ocean.AwemesReq\x1a\x11.ocean.AwemesResp\x12N\n" +
	"\x11VideoCoverSuggest\x12\x1b.ocean.VideoCoverSuggestReq\x1a\x1c.ocean.VideoCoverSuggestResp\x12<\n" +
	"\vFileImageAd\x12\x15.ocean.FileImageAdReq\x1a\x16.ocean.FileImageAdResp\x12W\n" +
	"\x14FileUploadTaskCreate\x12\x1e.ocean.FileUploadTaskCreateReq\x1a\x1f.ocean.FileUploadTaskCreateResp\x12Q\n" +
	"\x12FileUploadTaskList\x12\x1c.ocean.FileUploadTaskListReq\x1a\x1d.ocean.FileUploadTaskListResp\x12?\n" +
	"\fMicroAppList\x12\x16.ocean.MicroAppListReq\x1a\x17.ocean.MicroAppListResp\x12B\n" +
	"\rAssetLinkList\x12\x17.ocean.AssetLinkListReq\x1a\x18.ocean.AssetLinkListResp\x12H\n" +
	"\x0fPromotionCreate\x12\x19.ocean.PromotionCreateReq\x1a\x1a.ocean.PromotionCreateResp\x12B\n" +
	"\rProjectCreate\x12\x17.ocean.ProjectCreateReq\x1a\x18.ocean.ProjectCreateResp\x126\n" +
	"\x0fReportCustomGet\x12\x10.ocean.ReportReq\x1a\x11.ocean.ReportRespB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var file_ocean_proto_goTypes = []any{
	(*QueueLenReq)(nil),              // 0: ocean.QueueLenReq
	(*AwemesReq)(nil),                // 1: ocean.AwemesReq
	(*VideoCoverSuggestReq)(nil),     // 2: ocean.VideoCoverSuggestReq
	(*FileImageAdReq)(nil),           // 3: ocean.FileImageAdReq
	(*FileUploadTaskCreateReq)(nil),  // 4: ocean.FileUploadTaskCreateReq
	(*FileUploadTaskListReq)(nil),    // 5: ocean.FileUploadTaskListReq
	(*MicroAppListReq)(nil),          // 6: ocean.MicroAppListReq
	(*AssetLinkListReq)(nil),         // 7: ocean.AssetLinkListReq
	(*PromotionCreateReq)(nil),       // 8: ocean.PromotionCreateReq
	(*ProjectCreateReq)(nil),         // 9: ocean.ProjectCreateReq
	(*ReportReq)(nil),                // 10: ocean.ReportReq
	(*QueueLenResp)(nil),             // 11: ocean.QueueLenResp
	(*AwemesResp)(nil),               // 12: ocean.AwemesResp
	(*VideoCoverSuggestResp)(nil),    // 13: ocean.VideoCoverSuggestResp
	(*FileImageAdResp)(nil),          // 14: ocean.FileImageAdResp
	(*FileUploadTaskCreateResp)(nil), // 15: ocean.FileUploadTaskCreateResp
	(*FileUploadTaskListResp)(nil),   // 16: ocean.FileUploadTaskListResp
	(*MicroAppListResp)(nil),         // 17: ocean.MicroAppListResp
	(*AssetLinkListResp)(nil),        // 18: ocean.AssetLinkListResp
	(*PromotionCreateResp)(nil),      // 19: ocean.PromotionCreateResp
	(*ProjectCreateResp)(nil),        // 20: ocean.ProjectCreateResp
	(*ReportResp)(nil),               // 21: ocean.ReportResp
}
var file_ocean_proto_depIdxs = []int32{
	0,  // 0: ocean.Api.QueueLen:input_type -> ocean.QueueLenReq
	1,  // 1: ocean.Api.Awemes:input_type -> ocean.AwemesReq
	2,  // 2: ocean.Api.VideoCoverSuggest:input_type -> ocean.VideoCoverSuggestReq
	3,  // 3: ocean.Api.FileImageAd:input_type -> ocean.FileImageAdReq
	4,  // 4: ocean.Api.FileUploadTaskCreate:input_type -> ocean.FileUploadTaskCreateReq
	5,  // 5: ocean.Api.FileUploadTaskList:input_type -> ocean.FileUploadTaskListReq
	6,  // 6: ocean.Api.MicroAppList:input_type -> ocean.MicroAppListReq
	7,  // 7: ocean.Api.AssetLinkList:input_type -> ocean.AssetLinkListReq
	8,  // 8: ocean.Api.PromotionCreate:input_type -> ocean.PromotionCreateReq
	9,  // 9: ocean.Api.ProjectCreate:input_type -> ocean.ProjectCreateReq
	10, // 10: ocean.Api.ReportCustomGet:input_type -> ocean.ReportReq
	11, // 11: ocean.Api.QueueLen:output_type -> ocean.QueueLenResp
	12, // 12: ocean.Api.Awemes:output_type -> ocean.AwemesResp
	13, // 13: ocean.Api.VideoCoverSuggest:output_type -> ocean.VideoCoverSuggestResp
	14, // 14: ocean.Api.FileImageAd:output_type -> ocean.FileImageAdResp
	15, // 15: ocean.Api.FileUploadTaskCreate:output_type -> ocean.FileUploadTaskCreateResp
	16, // 16: ocean.Api.FileUploadTaskList:output_type -> ocean.FileUploadTaskListResp
	17, // 17: ocean.Api.MicroAppList:output_type -> ocean.MicroAppListResp
	18, // 18: ocean.Api.AssetLinkList:output_type -> ocean.AssetLinkListResp
	19, // 19: ocean.Api.PromotionCreate:output_type -> ocean.PromotionCreateResp
	20, // 20: ocean.Api.ProjectCreate:output_type -> ocean.ProjectCreateResp
	21, // 21: ocean.Api.ReportCustomGet:output_type -> ocean.ReportResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ocean_proto_init() }
func file_ocean_proto_init() {
	if File_ocean_proto != nil {
		return
	}
	file_tools_proto_init()
	file_status_proto_init()
	file_material_proto_init()
	file_promotion_proto_init()
	file_project_proto_init()
	file_report_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocean_proto_rawDesc), len(file_ocean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocean_proto_goTypes,
		DependencyIndexes: file_ocean_proto_depIdxs,
	}.Build()
	File_ocean_proto = out.File
	file_ocean_proto_goTypes = nil
	file_ocean_proto_depIdxs = nil
}
