// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: project.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectCreateReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Conf          *Conf                   `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *ProjectCreateReqParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateReq) Reset() {
	*x = ProjectCreateReq{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateReq) ProtoMessage() {}

func (x *ProjectCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateReq.ProtoReflect.Descriptor instead.
func (*ProjectCreateReq) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectCreateReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *ProjectCreateReq) GetParams() *ProjectCreateReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ProjectCreateReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  int64                  `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateReqParams) Reset() {
	*x = ProjectCreateReqParams{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateReqParams) ProtoMessage() {}

func (x *ProjectCreateReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateReqParams.ProtoReflect.Descriptor instead.
func (*ProjectCreateReqParams) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectCreateReqParams) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *ProjectCreateReqParams) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ProjectCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *ProjectCreateData     `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateResp) Reset() {
	*x = ProjectCreateResp{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateResp) ProtoMessage() {}

func (x *ProjectCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateResp.ProtoReflect.Descriptor instead.
func (*ProjectCreateResp) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectCreateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProjectCreateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProjectCreateResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProjectCreateResp) GetData() *ProjectCreateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProjectCreateData struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	ProjectId                  int64                       `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SupplementaryAgreementInfo string                      `protobuf:"bytes,2,opt,name=supplementary_agreement_info,json=supplementaryAgreementInfo,proto3" json:"supplementary_agreement_info,omitempty"`
	AutoProjectCount           int32                       `protobuf:"varint,3,opt,name=auto_project_count,json=autoProjectCount,proto3" json:"auto_project_count,omitempty"`
	ErrorKeywordsList          []*ProjectErrorKeywordsList `protobuf:"bytes,4,rep,name=error_keywords_list,json=errorKeywordsList,proto3" json:"error_keywords_list,omitempty"`
	AutoDurationProjectCount   int32                       `protobuf:"varint,5,opt,name=auto_duration_project_count,json=autoDurationProjectCount,proto3" json:"auto_duration_project_count,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ProjectCreateData) Reset() {
	*x = ProjectCreateData{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateData) ProtoMessage() {}

func (x *ProjectCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateData.ProtoReflect.Descriptor instead.
func (*ProjectCreateData) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectCreateData) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectCreateData) GetSupplementaryAgreementInfo() string {
	if x != nil {
		return x.SupplementaryAgreementInfo
	}
	return ""
}

func (x *ProjectCreateData) GetAutoProjectCount() int32 {
	if x != nil {
		return x.AutoProjectCount
	}
	return 0
}

func (x *ProjectCreateData) GetErrorKeywordsList() []*ProjectErrorKeywordsList {
	if x != nil {
		return x.ErrorKeywordsList
	}
	return nil
}

func (x *ProjectCreateData) GetAutoDurationProjectCount() int32 {
	if x != nil {
		return x.AutoDurationProjectCount
	}
	return 0
}

type ProjectErrorKeywordsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorKeyword  string                 `protobuf:"bytes,1,opt,name=error_keyword,json=errorKeyword,proto3" json:"error_keyword,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectErrorKeywordsList) Reset() {
	*x = ProjectErrorKeywordsList{}
	mi := &file_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectErrorKeywordsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectErrorKeywordsList) ProtoMessage() {}

func (x *ProjectErrorKeywordsList) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectErrorKeywordsList.ProtoReflect.Descriptor instead.
func (*ProjectErrorKeywordsList) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectErrorKeywordsList) GetErrorKeyword() string {
	if x != nil {
		return x.ErrorKeyword
	}
	return ""
}

func (x *ProjectErrorKeywordsList) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"i\n" +
	"\x10ProjectCreateReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x125\n" +
	"\x06params\x18\x02 \x01(\v2\x1d.ocean.ProjectCreateReqParamsR\x06params\"Q\n" +
	"\x16ProjectCreateReqParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x03R\fadvertiserId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"\x8e\x01\n" +
	"\x11ProjectCreateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12,\n" +
	"\x04data\x18\x04 \x01(\v2\x18.ocean.ProjectCreateDataR\x04data\"\xb2\x02\n" +
	"\x11ProjectCreateData\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12@\n" +
	"\x1csupplementary_agreement_info\x18\x02 \x01(\tR\x1asupplementaryAgreementInfo\x12,\n" +
	"\x12auto_project_count\x18\x03 \x01(\x05R\x10autoProjectCount\x12O\n" +
	"\x13error_keywords_list\x18\x04 \x03(\v2\x1f.ocean.ProjectErrorKeywordsListR\x11errorKeywordsList\x12=\n" +
	"\x1bauto_duration_project_count\x18\x05 \x01(\x05R\x18autoDurationProjectCount\"d\n" +
	"\x18ProjectErrorKeywordsList\x12#\n" +
	"\rerror_keyword\x18\x01 \x01(\tR\ferrorKeyword\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_project_proto_goTypes = []any{
	(*ProjectCreateReq)(nil),         // 0: ocean.ProjectCreateReq
	(*ProjectCreateReqParams)(nil),   // 1: ocean.ProjectCreateReqParams
	(*ProjectCreateResp)(nil),        // 2: ocean.ProjectCreateResp
	(*ProjectCreateData)(nil),        // 3: ocean.ProjectCreateData
	(*ProjectErrorKeywordsList)(nil), // 4: ocean.ProjectErrorKeywordsList
	(*Conf)(nil),                     // 5: conf.Conf
}
var file_project_proto_depIdxs = []int32{
	5, // 0: ocean.ProjectCreateReq.conf:type_name -> conf.Conf
	1, // 1: ocean.ProjectCreateReq.params:type_name -> ocean.ProjectCreateReqParams
	3, // 2: ocean.ProjectCreateResp.data:type_name -> ocean.ProjectCreateData
	4, // 3: ocean.ProjectCreateData.error_keywords_list:type_name -> ocean.ProjectErrorKeywordsList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
