// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: promotion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromotionCreateReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Conf          *Conf                     `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *PromotionCreateReqParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionCreateReq) Reset() {
	*x = PromotionCreateReq{}
	mi := &file_promotion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionCreateReq) ProtoMessage() {}

func (x *PromotionCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionCreateReq.ProtoReflect.Descriptor instead.
func (*PromotionCreateReq) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *PromotionCreateReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *PromotionCreateReq) GetParams() *PromotionCreateReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type PromotionCreateReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  int64                  `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionCreateReqParams) Reset() {
	*x = PromotionCreateReqParams{}
	mi := &file_promotion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionCreateReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionCreateReqParams) ProtoMessage() {}

func (x *PromotionCreateReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionCreateReqParams.ProtoReflect.Descriptor instead.
func (*PromotionCreateReqParams) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *PromotionCreateReqParams) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *PromotionCreateReqParams) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PromotionCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *PromotionCreateData   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionCreateResp) Reset() {
	*x = PromotionCreateResp{}
	mi := &file_promotion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionCreateResp) ProtoMessage() {}

func (x *PromotionCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionCreateResp.ProtoReflect.Descriptor instead.
func (*PromotionCreateResp) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *PromotionCreateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PromotionCreateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PromotionCreateResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PromotionCreateResp) GetData() *PromotionCreateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PromotionCreateData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PromotionId       int64                  `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	ErrorKeywordsList []*ErrorKeywordsList   `protobuf:"bytes,2,rep,name=error_keywords_list,json=errorKeywordsList,proto3" json:"error_keywords_list,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromotionCreateData) Reset() {
	*x = PromotionCreateData{}
	mi := &file_promotion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionCreateData) ProtoMessage() {}

func (x *PromotionCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionCreateData.ProtoReflect.Descriptor instead.
func (*PromotionCreateData) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *PromotionCreateData) GetPromotionId() int64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *PromotionCreateData) GetErrorKeywordsList() []*ErrorKeywordsList {
	if x != nil {
		return x.ErrorKeywordsList
	}
	return nil
}

type ErrorKeywordsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorKeyword  string                 `protobuf:"bytes,1,opt,name=error_keyword,json=errorKeyword,proto3" json:"error_keyword,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorKeywordsList) Reset() {
	*x = ErrorKeywordsList{}
	mi := &file_promotion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorKeywordsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorKeywordsList) ProtoMessage() {}

func (x *ErrorKeywordsList) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorKeywordsList.ProtoReflect.Descriptor instead.
func (*ErrorKeywordsList) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorKeywordsList) GetErrorKeyword() string {
	if x != nil {
		return x.ErrorKeyword
	}
	return ""
}

func (x *ErrorKeywordsList) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_promotion_proto protoreflect.FileDescriptor

const file_promotion_proto_rawDesc = "" +
	"\n" +
	"\x0fpromotion.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"m\n" +
	"\x12PromotionCreateReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x127\n" +
	"\x06params\x18\x02 \x01(\v2\x1f.ocean.PromotionCreateReqParamsR\x06params\"S\n" +
	"\x18PromotionCreateReqParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x03R\fadvertiserId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"\x92\x01\n" +
	"\x13PromotionCreateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12.\n" +
	"\x04data\x18\x04 \x01(\v2\x1a.ocean.PromotionCreateDataR\x04data\"\x82\x01\n" +
	"\x13PromotionCreateData\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\x03R\vpromotionId\x12H\n" +
	"\x13error_keywords_list\x18\x02 \x03(\v2\x18.ocean.ErrorKeywordsListR\x11errorKeywordsList\"]\n" +
	"\x11ErrorKeywordsList\x12#\n" +
	"\rerror_keyword\x18\x01 \x01(\tR\ferrorKeyword\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_promotion_proto_rawDescOnce sync.Once
	file_promotion_proto_rawDescData []byte
)

func file_promotion_proto_rawDescGZIP() []byte {
	file_promotion_proto_rawDescOnce.Do(func() {
		file_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promotion_proto_rawDesc), len(file_promotion_proto_rawDesc)))
	})
	return file_promotion_proto_rawDescData
}

var file_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_promotion_proto_goTypes = []any{
	(*PromotionCreateReq)(nil),       // 0: ocean.PromotionCreateReq
	(*PromotionCreateReqParams)(nil), // 1: ocean.PromotionCreateReqParams
	(*PromotionCreateResp)(nil),      // 2: ocean.PromotionCreateResp
	(*PromotionCreateData)(nil),      // 3: ocean.PromotionCreateData
	(*ErrorKeywordsList)(nil),        // 4: ocean.ErrorKeywordsList
	(*Conf)(nil),                     // 5: conf.Conf
}
var file_promotion_proto_depIdxs = []int32{
	5, // 0: ocean.PromotionCreateReq.conf:type_name -> conf.Conf
	1, // 1: ocean.PromotionCreateReq.params:type_name -> ocean.PromotionCreateReqParams
	3, // 2: ocean.PromotionCreateResp.data:type_name -> ocean.PromotionCreateData
	4, // 3: ocean.PromotionCreateData.error_keywords_list:type_name -> ocean.ErrorKeywordsList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_promotion_proto_init() }
func file_promotion_proto_init() {
	if File_promotion_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promotion_proto_rawDesc), len(file_promotion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_promotion_proto_goTypes,
		DependencyIndexes: file_promotion_proto_depIdxs,
		MessageInfos:      file_promotion_proto_msgTypes,
	}.Build()
	File_promotion_proto = out.File
	file_promotion_proto_goTypes = nil
	file_promotion_proto_depIdxs = nil
}
