// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: qps.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeQpsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullMethod    string                 `protobuf:"bytes,1,opt,name=fullMethod,proto3" json:"fullMethod,omitempty"`
	DevKey        string                 `protobuf:"bytes,2,opt,name=devKey,proto3" json:"devKey,omitempty"`
	Qps           int32                  `protobuf:"varint,3,opt,name=qps,proto3" json:"qps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeQpsReq) Reset() {
	*x = ChangeQpsReq{}
	mi := &file_qps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeQpsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeQpsReq) ProtoMessage() {}

func (x *ChangeQpsReq) ProtoReflect() protoreflect.Message {
	mi := &file_qps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeQpsReq.ProtoReflect.Descriptor instead.
func (*ChangeQpsReq) Descriptor() ([]byte, []int) {
	return file_qps_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeQpsReq) GetFullMethod() string {
	if x != nil {
		return x.FullMethod
	}
	return ""
}

func (x *ChangeQpsReq) GetDevKey() string {
	if x != nil {
		return x.DevKey
	}
	return ""
}

func (x *ChangeQpsReq) GetQps() int32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

type ChangeQpsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeQpsResp) Reset() {
	*x = ChangeQpsResp{}
	mi := &file_qps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeQpsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeQpsResp) ProtoMessage() {}

func (x *ChangeQpsResp) ProtoReflect() protoreflect.Message {
	mi := &file_qps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeQpsResp.ProtoReflect.Descriptor instead.
func (*ChangeQpsResp) Descriptor() ([]byte, []int) {
	return file_qps_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeQpsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChangeQpsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestReq) Reset() {
	*x = TestReq{}
	mi := &file_qps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReq) ProtoMessage() {}

func (x *TestReq) ProtoReflect() protoreflect.Message {
	mi := &file_qps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReq.ProtoReflect.Descriptor instead.
func (*TestReq) Descriptor() ([]byte, []int) {
	return file_qps_proto_rawDescGZIP(), []int{2}
}

func (x *TestReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *TestReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type TestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResp) Reset() {
	*x = TestResp{}
	mi := &file_qps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResp) ProtoMessage() {}

func (x *TestResp) ProtoReflect() protoreflect.Message {
	mi := &file_qps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResp.ProtoReflect.Descriptor instead.
func (*TestResp) Descriptor() ([]byte, []int) {
	return file_qps_proto_rawDescGZIP(), []int{3}
}

func (x *TestResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TestResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_qps_proto protoreflect.FileDescriptor

const file_qps_proto_rawDesc = "" +
	"\n" +
	"\tqps.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"X\n" +
	"\fChangeQpsReq\x12\x1e\n" +
	"\n" +
	"fullMethod\x18\x01 \x01(\tR\n" +
	"fullMethod\x12\x16\n" +
	"\x06devKey\x18\x02 \x01(\tR\x06devKey\x12\x10\n" +
	"\x03qps\x18\x03 \x01(\x05R\x03qps\"=\n" +
	"\rChangeQpsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\aTestReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"8\n" +
	"\bTestResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_qps_proto_rawDescOnce sync.Once
	file_qps_proto_rawDescData []byte
)

func file_qps_proto_rawDescGZIP() []byte {
	file_qps_proto_rawDescOnce.Do(func() {
		file_qps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qps_proto_rawDesc), len(file_qps_proto_rawDesc)))
	})
	return file_qps_proto_rawDescData
}

var file_qps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qps_proto_goTypes = []any{
	(*ChangeQpsReq)(nil),  // 0: ocean.ChangeQpsReq
	(*ChangeQpsResp)(nil), // 1: ocean.ChangeQpsResp
	(*TestReq)(nil),       // 2: ocean.TestReq
	(*TestResp)(nil),      // 3: ocean.TestResp
	(*Conf)(nil),          // 4: conf.Conf
}
var file_qps_proto_depIdxs = []int32{
	4, // 0: ocean.TestReq.conf:type_name -> conf.Conf
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_qps_proto_init() }
func file_qps_proto_init() {
	if File_qps_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qps_proto_rawDesc), len(file_qps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qps_proto_goTypes,
		DependencyIndexes: file_qps_proto_depIdxs,
		MessageInfos:      file_qps_proto_msgTypes,
	}.Build()
	File_qps_proto = out.File
	file_qps_proto_goTypes = nil
	file_qps_proto_depIdxs = nil
}
