// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: report.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterType int32

const (
	FilterType_FILTER_TYPE_UNSPECIFIED FilterType = 0
	FilterType_FILTER_TYPE_ENUM        FilterType = 1 //1 -固定枚举值
	FilterType_FILTER_TYPE_NUMBER      FilterType = 2 //2 - 固定输入值
	FilterType_FILTER_TYPE_STRING      FilterType = 3 //3 -数值类型
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "FILTER_TYPE_UNSPECIFIED",
		1: "FILTER_TYPE_ENUM",
		2: "FILTER_TYPE_NUMBER",
		3: "FILTER_TYPE_STRING",
	}
	FilterType_value = map[string]int32{
		"FILTER_TYPE_UNSPECIFIED": 0,
		"FILTER_TYPE_ENUM":        1,
		"FILTER_TYPE_NUMBER":      2,
		"FILTER_TYPE_STRING":      3,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[0].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[0]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_EQUAL                Operator = 1 // =
	Operator_NOT_EQUAL            Operator = 2 // !=
	Operator_GT                   Operator = 3 // >
	Operator_GTE                  Operator = 4 // >=
	Operator_LT                   Operator = 5 // <
	Operator_LTE                  Operator = 6 // <=
	Operator_IN                   Operator = 7 // IN
	Operator_NOT_IN               Operator = 8 // NOT IN
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "EQUAL",
		2: "NOT_EQUAL",
		3: "GT",
		4: "GTE",
		5: "LT",
		6: "LTE",
		7: "IN",
		8: "NOT_IN",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"EQUAL":                1,
		"NOT_EQUAL":            2,
		"GT":                   3,
		"GTE":                  4,
		"LT":                   5,
		"LTE":                  6,
		"IN":                   7,
		"NOT_IN":               8,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[1].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[1]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

type ReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *ReportReqParams       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReq) Reset() {
	*x = ReportReq{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReq) ProtoMessage() {}

func (x *ReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReq.ProtoReflect.Descriptor instead.
func (*ReportReq) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *ReportReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *ReportReq) GetParams() *ReportReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ReportReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  int64                  `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Dimensions    []string               `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Metrics       []string               `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	OrderBy       []*OrderBy             `protobuf:"bytes,6,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReqParams) Reset() {
	*x = ReportReqParams{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReqParams) ProtoMessage() {}

func (x *ReportReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReqParams.ProtoReflect.Descriptor instead.
func (*ReportReqParams) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *ReportReqParams) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *ReportReqParams) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *ReportReqParams) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ReportReqParams) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ReportReqParams) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ReportReqParams) GetOrderBy() []*OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *ReportReqParams) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReportReqParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReportReqParams) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *OrderBy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderBy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Type          FilterType             `protobuf:"varint,2,opt,name=type,proto3,enum=ocean.FilterType" json:"type,omitempty"`
	Operator      Operator               `protobuf:"varint,3,opt,name=operator,proto3,enum=ocean.Operator" json:"operator,omitempty"`
	Values        []string               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_FILTER_TYPE_UNSPECIFIED
}

func (x *Filter) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ReportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ReportData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResp) Reset() {
	*x = ReportResp{}
	mi := &file_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResp) ProtoMessage() {}

func (x *ReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResp.ProtoReflect.Descriptor instead.
func (*ReportResp) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{4}
}

func (x *ReportResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReportResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResp) GetData() *ReportData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReportResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReportData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ReportRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	TotalMetrics  map[string]string      `protobuf:"bytes,3,rep,name=total_metrics,json=totalMetrics,proto3" json:"total_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportData) Reset() {
	*x = ReportData{}
	mi := &file_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportData) ProtoMessage() {}

func (x *ReportData) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportData.ProtoReflect.Descriptor instead.
func (*ReportData) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{5}
}

func (x *ReportData) GetRows() []*ReportRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ReportData) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ReportData) GetTotalMetrics() map[string]string {
	if x != nil {
		return x.TotalMetrics
	}
	return nil
}

type ReportRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimensions    map[string]string      `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics       map[string]string      `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRow) Reset() {
	*x = ReportRow{}
	mi := &file_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRow) ProtoMessage() {}

func (x *ReportRow) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRow.ProtoReflect.Descriptor instead.
func (*ReportRow) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{6}
}

func (x *ReportRow) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *ReportRow) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"[\n" +
	"\tReportReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x12.\n" +
	"\x06params\x18\x02 \x01(\v2\x16.ocean.ReportReqParamsR\x06params\"\xaf\x02\n" +
	"\x0fReportReqParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x03R\fadvertiserId\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\tR\n" +
	"dimensions\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\tR\ametrics\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12)\n" +
	"\border_by\x18\x06 \x03(\v2\x0e.ocean.OrderByR\aorderBy\x12'\n" +
	"\afilters\x18\a \x03(\v2\r.ocean.FilterR\afilters\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\"3\n" +
	"\aOrderBy\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x8a\x01\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.ocean.FilterTypeR\x04type\x12+\n" +
	"\boperator\x18\x03 \x01(\x0e2\x0f.ocean.OperatorR\boperator\x12\x16\n" +
	"\x06values\x18\x04 \x03(\tR\x06values\"\x80\x01\n" +
	"\n" +
	"ReportResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x04data\x18\x03 \x01(\v2\x11.ocean.ReportDataR\x04data\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xea\x01\n" +
	"\n" +
	"ReportData\x12$\n" +
	"\x04rows\x18\x01 \x03(\v2\x10.ocean.ReportRowR\x04rows\x12+\n" +
	"\tpage_info\x18\x02 \x01(\v2\x0e.conf.PageInfoR\bpageInfo\x12H\n" +
	"\rtotal_metrics\x18\x03 \x03(\v2#.ocean.ReportData.TotalMetricsEntryR\ftotalMetrics\x1a?\n" +
	"\x11TotalMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\tReportRow\x12@\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v2 .ocean.ReportRow.DimensionsEntryR\n" +
	"dimensions\x127\n" +
	"\ametrics\x18\x02 \x03(\v2\x1d.ocean.ReportRow.MetricsEntryR\ametrics\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*o\n" +
	"\n" +
	"FilterType\x12\x1b\n" +
	"\x17FILTER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FILTER_TYPE_ENUM\x10\x01\x12\x16\n" +
	"\x12FILTER_TYPE_NUMBER\x10\x02\x12\x16\n" +
	"\x12FILTER_TYPE_STRING\x10\x03*t\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EQUAL\x10\x01\x12\r\n" +
	"\tNOT_EQUAL\x10\x02\x12\x06\n" +
	"\x02GT\x10\x03\x12\a\n" +
	"\x03GTE\x10\x04\x12\x06\n" +
	"\x02LT\x10\x05\x12\a\n" +
	"\x03LTE\x10\x06\x12\x06\n" +
	"\x02IN\x10\a\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\bB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_report_proto_goTypes = []any{
	(FilterType)(0),         // 0: ocean.FilterType
	(Operator)(0),           // 1: ocean.Operator
	(*ReportReq)(nil),       // 2: ocean.ReportReq
	(*ReportReqParams)(nil), // 3: ocean.ReportReqParams
	(*OrderBy)(nil),         // 4: ocean.OrderBy
	(*Filter)(nil),          // 5: ocean.Filter
	(*ReportResp)(nil),      // 6: ocean.ReportResp
	(*ReportData)(nil),      // 7: ocean.ReportData
	(*ReportRow)(nil),       // 8: ocean.ReportRow
	nil,                     // 9: ocean.ReportData.TotalMetricsEntry
	nil,                     // 10: ocean.ReportRow.DimensionsEntry
	nil,                     // 11: ocean.ReportRow.MetricsEntry
	(*Conf)(nil),            // 12: conf.Conf
	(*PageInfo)(nil),        // 13: conf.PageInfo
}
var file_report_proto_depIdxs = []int32{
	12, // 0: ocean.ReportReq.conf:type_name -> conf.Conf
	3,  // 1: ocean.ReportReq.params:type_name -> ocean.ReportReqParams
	4,  // 2: ocean.ReportReqParams.order_by:type_name -> ocean.OrderBy
	5,  // 3: ocean.ReportReqParams.filters:type_name -> ocean.Filter
	0,  // 4: ocean.Filter.type:type_name -> ocean.FilterType
	1,  // 5: ocean.Filter.operator:type_name -> ocean.Operator
	7,  // 6: ocean.ReportResp.data:type_name -> ocean.ReportData
	8,  // 7: ocean.ReportData.rows:type_name -> ocean.ReportRow
	13, // 8: ocean.ReportData.page_info:type_name -> conf.PageInfo
	9,  // 9: ocean.ReportData.total_metrics:type_name -> ocean.ReportData.TotalMetricsEntry
	10, // 10: ocean.ReportRow.dimensions:type_name -> ocean.ReportRow.DimensionsEntry
	11, // 11: ocean.ReportRow.metrics:type_name -> ocean.ReportRow.MetricsEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		EnumInfos:         file_report_proto_enumTypes,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
