// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueLenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 接口名称=rpc方法名
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// 必传，本次请求的优先级
	Priority Priority `protobuf:"varint,2,opt,name=priority,proto3,enum=conf.Priority" json:"priority,omitempty"`
	// 应用编号，默认值不传=0表示使用默认应用。传入特定编号时，各应用使用独立的频控策略
	AppNo         uint64 `protobuf:"varint,3,opt,name=app_no,json=appNo,proto3" json:"app_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueLenReq) Reset() {
	*x = QueueLenReq{}
	mi := &file_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueLenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueLenReq) ProtoMessage() {}

func (x *QueueLenReq) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueLenReq.ProtoReflect.Descriptor instead.
func (*QueueLenReq) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

func (x *QueueLenReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *QueueLenReq) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_Low
}

func (x *QueueLenReq) GetAppNo() uint64 {
	if x != nil {
		return x.AppNo
	}
	return 0
}

type QueueLenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueLenResp) Reset() {
	*x = QueueLenResp{}
	mi := &file_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueLenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueLenResp) ProtoMessage() {}

func (x *QueueLenResp) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueLenResp.ProtoReflect.Descriptor instead.
func (*QueueLenResp) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{1}
}

func (x *QueueLenResp) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_status_proto protoreflect.FileDescriptor

const file_status_proto_rawDesc = "" +
	"\n" +
	"\fstatus.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"h\n" +
	"\vQueueLenReq\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12*\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x0e.conf.PriorityR\bpriority\x12\x15\n" +
	"\x06app_no\x18\x03 \x01(\x04R\x05appNo\"&\n" +
	"\fQueueLenResp\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06lengthB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_status_proto_rawDescOnce sync.Once
	file_status_proto_rawDescData []byte
)

func file_status_proto_rawDescGZIP() []byte {
	file_status_proto_rawDescOnce.Do(func() {
		file_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)))
	})
	return file_status_proto_rawDescData
}

var file_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_status_proto_goTypes = []any{
	(*QueueLenReq)(nil),  // 0: ocean.QueueLenReq
	(*QueueLenResp)(nil), // 1: ocean.QueueLenResp
	(Priority)(0),        // 2: conf.Priority
}
var file_status_proto_depIdxs = []int32{
	2, // 0: ocean.QueueLenReq.priority:type_name -> conf.Priority
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_status_proto_init() }
func file_status_proto_init() {
	if File_status_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_status_proto_goTypes,
		DependencyIndexes: file_status_proto_depIdxs,
		MessageInfos:      file_status_proto_msgTypes,
	}.Build()
	File_status_proto = out.File
	file_status_proto_goTypes = nil
	file_status_proto_depIdxs = nil
}
