// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: tools.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SharedAdvertiser struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SharedAdvertiserId   int64                  `protobuf:"varint,1,opt,name=shared_advertiser_id,json=sharedAdvertiserId,proto3" json:"shared_advertiser_id,omitempty"`
	SharedAdvertiserName string                 `protobuf:"bytes,2,opt,name=shared_advertiser_name,json=sharedAdvertiserName,proto3" json:"shared_advertiser_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SharedAdvertiser) Reset() {
	*x = SharedAdvertiser{}
	mi := &file_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedAdvertiser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedAdvertiser) ProtoMessage() {}

func (x *SharedAdvertiser) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedAdvertiser.ProtoReflect.Descriptor instead.
func (*SharedAdvertiser) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0}
}

func (x *SharedAdvertiser) GetSharedAdvertiserId() int64 {
	if x != nil {
		return x.SharedAdvertiserId
	}
	return 0
}

func (x *SharedAdvertiser) GetSharedAdvertiserName() string {
	if x != nil {
		return x.SharedAdvertiserName
	}
	return ""
}

type AwemesData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId         uint64                 `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	AdvertiserName       string                 `protobuf:"bytes,2,opt,name=advertiser_name,json=advertiserName,proto3" json:"advertiser_name,omitempty"`
	IesId                uint64                 `protobuf:"varint,3,opt,name=ies_id,json=iesId,proto3" json:"ies_id,omitempty"`
	IesUserName          string                 `protobuf:"bytes,4,opt,name=ies_user_name,json=iesUserName,proto3" json:"ies_user_name,omitempty"`
	AwemeId              string                 `protobuf:"bytes,5,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	AwemeName            string                 `protobuf:"bytes,6,opt,name=aweme_name,json=awemeName,proto3" json:"aweme_name,omitempty"`
	AwemeAvatar          string                 `protobuf:"bytes,7,opt,name=aweme_avatar,json=awemeAvatar,proto3" json:"aweme_avatar,omitempty"`
	BindType             string                 `protobuf:"bytes,8,opt,name=bind_type,json=bindType,proto3" json:"bind_type,omitempty"`
	Status               string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	LeftDays             uint32                 `protobuf:"varint,10,opt,name=left_days,json=leftDays,proto3" json:"left_days,omitempty"`
	StartTime            string                 `protobuf:"bytes,11,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	SharedAdvertiserName string                 `protobuf:"bytes,12,opt,name=shared_advertiser_name,json=sharedAdvertiserName,proto3" json:"shared_advertiser_name,omitempty"`
	CommerceUserLevel    string                 `protobuf:"bytes,13,opt,name=commerce_user_level,json=commerceUserLevel,proto3" json:"commerce_user_level,omitempty"`
	SharedAdvertisers    []*SharedAdvertiser    `protobuf:"bytes,14,rep,name=shared_advertisers,json=sharedAdvertisers,proto3" json:"shared_advertisers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AwemesData) Reset() {
	*x = AwemesData{}
	mi := &file_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesData) ProtoMessage() {}

func (x *AwemesData) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesData.ProtoReflect.Descriptor instead.
func (*AwemesData) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{1}
}

func (x *AwemesData) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *AwemesData) GetAdvertiserName() string {
	if x != nil {
		return x.AdvertiserName
	}
	return ""
}

func (x *AwemesData) GetIesId() uint64 {
	if x != nil {
		return x.IesId
	}
	return 0
}

func (x *AwemesData) GetIesUserName() string {
	if x != nil {
		return x.IesUserName
	}
	return ""
}

func (x *AwemesData) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *AwemesData) GetAwemeName() string {
	if x != nil {
		return x.AwemeName
	}
	return ""
}

func (x *AwemesData) GetAwemeAvatar() string {
	if x != nil {
		return x.AwemeAvatar
	}
	return ""
}

func (x *AwemesData) GetBindType() string {
	if x != nil {
		return x.BindType
	}
	return ""
}

func (x *AwemesData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AwemesData) GetLeftDays() uint32 {
	if x != nil {
		return x.LeftDays
	}
	return 0
}

func (x *AwemesData) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AwemesData) GetSharedAdvertiserName() string {
	if x != nil {
		return x.SharedAdvertiserName
	}
	return ""
}

func (x *AwemesData) GetCommerceUserLevel() string {
	if x != nil {
		return x.CommerceUserLevel
	}
	return ""
}

func (x *AwemesData) GetSharedAdvertisers() []*SharedAdvertiser {
	if x != nil {
		return x.SharedAdvertisers
	}
	return nil
}

type AwemesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *AwemesReqParams       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwemesReq) Reset() {
	*x = AwemesReq{}
	mi := &file_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesReq) ProtoMessage() {}

func (x *AwemesReq) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesReq.ProtoReflect.Descriptor instead.
func (*AwemesReq) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{2}
}

func (x *AwemesReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *AwemesReq) GetParams() *AwemesReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type AwemesReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  uint64                 `protobuf:"varint,2,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwemesReqParams) Reset() {
	*x = AwemesReqParams{}
	mi := &file_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesReqParams) ProtoMessage() {}

func (x *AwemesReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesReqParams.ProtoReflect.Descriptor instead.
func (*AwemesReqParams) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{3}
}

func (x *AwemesReqParams) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

type AwemesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []*AwemesData          `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwemesResp) Reset() {
	*x = AwemesResp{}
	mi := &file_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesResp) ProtoMessage() {}

func (x *AwemesResp) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesResp.ProtoReflect.Descriptor instead.
func (*AwemesResp) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{4}
}

func (x *AwemesResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AwemesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AwemesResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AwemesResp) GetData() []*AwemesData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_tools_proto protoreflect.FileDescriptor

const file_tools_proto_rawDesc = "" +
	"\n" +
	"\vtools.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"z\n" +
	"\x10SharedAdvertiser\x120\n" +
	"\x14shared_advertiser_id\x18\x01 \x01(\x03R\x12sharedAdvertiserId\x124\n" +
	"\x16shared_advertiser_name\x18\x02 \x01(\tR\x14sharedAdvertiserName\"\x91\x04\n" +
	"\n" +
	"AwemesData\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x04R\fadvertiserId\x12'\n" +
	"\x0fadvertiser_name\x18\x02 \x01(\tR\x0eadvertiserName\x12\x15\n" +
	"\x06ies_id\x18\x03 \x01(\x04R\x05iesId\x12\"\n" +
	"\ries_user_name\x18\x04 \x01(\tR\viesUserName\x12\x19\n" +
	"\baweme_id\x18\x05 \x01(\tR\aawemeId\x12\x1d\n" +
	"\n" +
	"aweme_name\x18\x06 \x01(\tR\tawemeName\x12!\n" +
	"\faweme_avatar\x18\a \x01(\tR\vawemeAvatar\x12\x1b\n" +
	"\tbind_type\x18\b \x01(\tR\bbindType\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1b\n" +
	"\tleft_days\x18\n" +
	" \x01(\rR\bleftDays\x12\x1d\n" +
	"\n" +
	"start_time\x18\v \x01(\tR\tstartTime\x124\n" +
	"\x16shared_advertiser_name\x18\f \x01(\tR\x14sharedAdvertiserName\x12.\n" +
	"\x13commerce_user_level\x18\r \x01(\tR\x11commerceUserLevel\x12F\n" +
	"\x12shared_advertisers\x18\x0e \x03(\v2\x17.ocean.SharedAdvertiserR\x11sharedAdvertisers\"[\n" +
	"\tAwemesReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x12.\n" +
	"\x06params\x18\x02 \x01(\v2\x16.ocean.AwemesReqParamsR\x06params\"6\n" +
	"\x0fAwemesReqParams\x12#\n" +
	"\radvertiser_id\x18\x02 \x01(\x04R\fadvertiserId\"\x80\x01\n" +
	"\n" +
	"AwemesResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12%\n" +
	"\x04data\x18\x05 \x03(\v2\x11.ocean.AwemesDataR\x04dataB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_tools_proto_rawDescOnce sync.Once
	file_tools_proto_rawDescData []byte
)

func file_tools_proto_rawDescGZIP() []byte {
	file_tools_proto_rawDescOnce.Do(func() {
		file_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)))
	})
	return file_tools_proto_rawDescData
}

var file_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tools_proto_goTypes = []any{
	(*SharedAdvertiser)(nil), // 0: ocean.SharedAdvertiser
	(*AwemesData)(nil),       // 1: ocean.AwemesData
	(*AwemesReq)(nil),        // 2: ocean.AwemesReq
	(*AwemesReqParams)(nil),  // 3: ocean.AwemesReqParams
	(*AwemesResp)(nil),       // 4: ocean.AwemesResp
	(*Conf)(nil),             // 5: conf.Conf
}
var file_tools_proto_depIdxs = []int32{
	0, // 0: ocean.AwemesData.shared_advertisers:type_name -> ocean.SharedAdvertiser
	5, // 1: ocean.AwemesReq.conf:type_name -> conf.Conf
	3, // 2: ocean.AwemesReq.params:type_name -> ocean.AwemesReqParams
	1, // 3: ocean.AwemesResp.data:type_name -> ocean.AwemesData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tools_proto_init() }
func file_tools_proto_init() {
	if File_tools_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tools_proto_goTypes,
		DependencyIndexes: file_tools_proto_depIdxs,
		MessageInfos:      file_tools_proto_msgTypes,
	}.Build()
	File_tools_proto = out.File
	file_tools_proto_goTypes = nil
	file_tools_proto_depIdxs = nil
}
