// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: tools.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SharedAdvertiser struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SharedAdvertiserId   int64                  `protobuf:"varint,1,opt,name=shared_advertiser_id,json=sharedAdvertiserId,proto3" json:"shared_advertiser_id,omitempty"`
	SharedAdvertiserName string                 `protobuf:"bytes,2,opt,name=shared_advertiser_name,json=sharedAdvertiserName,proto3" json:"shared_advertiser_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SharedAdvertiser) Reset() {
	*x = SharedAdvertiser{}
	mi := &file_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedAdvertiser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedAdvertiser) ProtoMessage() {}

func (x *SharedAdvertiser) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedAdvertiser.ProtoReflect.Descriptor instead.
func (*SharedAdvertiser) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0}
}

func (x *SharedAdvertiser) GetSharedAdvertiserId() int64 {
	if x != nil {
		return x.SharedAdvertiserId
	}
	return 0
}

func (x *SharedAdvertiser) GetSharedAdvertiserName() string {
	if x != nil {
		return x.SharedAdvertiserName
	}
	return ""
}

type AwemesData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId         uint64                 `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	AdvertiserName       string                 `protobuf:"bytes,2,opt,name=advertiser_name,json=advertiserName,proto3" json:"advertiser_name,omitempty"`
	IesId                uint64                 `protobuf:"varint,3,opt,name=ies_id,json=iesId,proto3" json:"ies_id,omitempty"`
	IesUserName          string                 `protobuf:"bytes,4,opt,name=ies_user_name,json=iesUserName,proto3" json:"ies_user_name,omitempty"`
	AwemeId              string                 `protobuf:"bytes,5,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	AwemeName            string                 `protobuf:"bytes,6,opt,name=aweme_name,json=awemeName,proto3" json:"aweme_name,omitempty"`
	AwemeAvatar          string                 `protobuf:"bytes,7,opt,name=aweme_avatar,json=awemeAvatar,proto3" json:"aweme_avatar,omitempty"`
	BindType             string                 `protobuf:"bytes,8,opt,name=bind_type,json=bindType,proto3" json:"bind_type,omitempty"`
	Status               string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	LeftDays             int32                  `protobuf:"varint,10,opt,name=left_days,json=leftDays,proto3" json:"left_days,omitempty"`
	StartTime            string                 `protobuf:"bytes,11,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	SharedAdvertiserName string                 `protobuf:"bytes,12,opt,name=shared_advertiser_name,json=sharedAdvertiserName,proto3" json:"shared_advertiser_name,omitempty"`
	CommerceUserLevel    string                 `protobuf:"bytes,13,opt,name=commerce_user_level,json=commerceUserLevel,proto3" json:"commerce_user_level,omitempty"`
	SharedAdvertisers    []*SharedAdvertiser    `protobuf:"bytes,14,rep,name=shared_advertisers,json=sharedAdvertisers,proto3" json:"shared_advertisers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AwemesData) Reset() {
	*x = AwemesData{}
	mi := &file_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesData) ProtoMessage() {}

func (x *AwemesData) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesData.ProtoReflect.Descriptor instead.
func (*AwemesData) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{1}
}

func (x *AwemesData) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *AwemesData) GetAdvertiserName() string {
	if x != nil {
		return x.AdvertiserName
	}
	return ""
}

func (x *AwemesData) GetIesId() uint64 {
	if x != nil {
		return x.IesId
	}
	return 0
}

func (x *AwemesData) GetIesUserName() string {
	if x != nil {
		return x.IesUserName
	}
	return ""
}

func (x *AwemesData) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *AwemesData) GetAwemeName() string {
	if x != nil {
		return x.AwemeName
	}
	return ""
}

func (x *AwemesData) GetAwemeAvatar() string {
	if x != nil {
		return x.AwemeAvatar
	}
	return ""
}

func (x *AwemesData) GetBindType() string {
	if x != nil {
		return x.BindType
	}
	return ""
}

func (x *AwemesData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AwemesData) GetLeftDays() int32 {
	if x != nil {
		return x.LeftDays
	}
	return 0
}

func (x *AwemesData) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AwemesData) GetSharedAdvertiserName() string {
	if x != nil {
		return x.SharedAdvertiserName
	}
	return ""
}

func (x *AwemesData) GetCommerceUserLevel() string {
	if x != nil {
		return x.CommerceUserLevel
	}
	return ""
}

func (x *AwemesData) GetSharedAdvertisers() []*SharedAdvertiser {
	if x != nil {
		return x.SharedAdvertisers
	}
	return nil
}

type AwemesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *AwemesReqParams       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwemesReq) Reset() {
	*x = AwemesReq{}
	mi := &file_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesReq) ProtoMessage() {}

func (x *AwemesReq) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesReq.ProtoReflect.Descriptor instead.
func (*AwemesReq) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{2}
}

func (x *AwemesReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *AwemesReq) GetParams() *AwemesReqParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type AwemesReqParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  uint64                 `protobuf:"varint,2,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwemesReqParams) Reset() {
	*x = AwemesReqParams{}
	mi := &file_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesReqParams) ProtoMessage() {}

func (x *AwemesReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesReqParams.ProtoReflect.Descriptor instead.
func (*AwemesReqParams) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{3}
}

func (x *AwemesReqParams) GetAdvertiserId() uint64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

type AwemesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []*AwemesData          `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwemesResp) Reset() {
	*x = AwemesResp{}
	mi := &file_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwemesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwemesResp) ProtoMessage() {}

func (x *AwemesResp) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwemesResp.ProtoReflect.Descriptor instead.
func (*AwemesResp) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{4}
}

func (x *AwemesResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AwemesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AwemesResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AwemesResp) GetData() []*AwemesData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MicroAppListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *MicroAppListParams    `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppListReq) Reset() {
	*x = MicroAppListReq{}
	mi := &file_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListReq) ProtoMessage() {}

func (x *MicroAppListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListReq.ProtoReflect.Descriptor instead.
func (*MicroAppListReq) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{5}
}

func (x *MicroAppListReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *MicroAppListReq) GetParams() *MicroAppListParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type MicroAppListParams struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	AdvertiserId  int64                        `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Filtering     *MicroAppListParamsFiltering `protobuf:"bytes,2,opt,name=filtering,proto3" json:"filtering,omitempty"`
	Page          int32                        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                        `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppListParams) Reset() {
	*x = MicroAppListParams{}
	mi := &file_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListParams) ProtoMessage() {}

func (x *MicroAppListParams) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListParams.ProtoReflect.Descriptor instead.
func (*MicroAppListParams) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{6}
}

func (x *MicroAppListParams) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *MicroAppListParams) GetFiltering() *MicroAppListParamsFiltering {
	if x != nil {
		return x.Filtering
	}
	return nil
}

func (x *MicroAppListParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MicroAppListParams) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MicroAppListParamsFiltering struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	SearchKey     string                           `protobuf:"bytes,1,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	AuditStatus   string                           `protobuf:"bytes,2,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	SearchType    string                           `protobuf:"bytes,3,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"`
	CreateTime    *MicroAppListParamsFilteringTime `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppListParamsFiltering) Reset() {
	*x = MicroAppListParamsFiltering{}
	mi := &file_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListParamsFiltering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListParamsFiltering) ProtoMessage() {}

func (x *MicroAppListParamsFiltering) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListParamsFiltering.ProtoReflect.Descriptor instead.
func (*MicroAppListParamsFiltering) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{7}
}

func (x *MicroAppListParamsFiltering) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *MicroAppListParamsFiltering) GetAuditStatus() string {
	if x != nil {
		return x.AuditStatus
	}
	return ""
}

func (x *MicroAppListParamsFiltering) GetSearchType() string {
	if x != nil {
		return x.SearchType
	}
	return ""
}

func (x *MicroAppListParamsFiltering) GetCreateTime() *MicroAppListParamsFilteringTime {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type MicroAppListParamsFilteringTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppListParamsFilteringTime) Reset() {
	*x = MicroAppListParamsFilteringTime{}
	mi := &file_tools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListParamsFilteringTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListParamsFilteringTime) ProtoMessage() {}

func (x *MicroAppListParamsFilteringTime) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListParamsFilteringTime.ProtoReflect.Descriptor instead.
func (*MicroAppListParamsFilteringTime) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{8}
}

func (x *MicroAppListParamsFilteringTime) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MicroAppListParamsFilteringTime) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type MicroAppListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *MicroAppListData      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppListResp) Reset() {
	*x = MicroAppListResp{}
	mi := &file_tools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListResp) ProtoMessage() {}

func (x *MicroAppListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListResp.ProtoReflect.Descriptor instead.
func (*MicroAppListResp) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{9}
}

func (x *MicroAppListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MicroAppListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MicroAppListResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MicroAppListResp) GetData() *MicroAppListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MicroAppListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MicroAppListItem    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppListData) Reset() {
	*x = MicroAppListData{}
	mi := &file_tools_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListData) ProtoMessage() {}

func (x *MicroAppListData) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListData.ProtoReflect.Descriptor instead.
func (*MicroAppListData) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{10}
}

func (x *MicroAppListData) GetList() []*MicroAppListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MicroAppListData) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type MicroAppListItem struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	InstanceId              int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Remark                  string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	AuditStatus             string                 `protobuf:"bytes,3,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	Reason                  string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	AdvertiserId            int64                  `protobuf:"varint,5,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	CreateTime              string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime              string                 `protobuf:"bytes,7,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	Name                    string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	TagInfo                 string                 `protobuf:"bytes,9,opt,name=tag_info,json=tagInfo,proto3" json:"tag_info,omitempty"`
	PaymentForm             string                 `protobuf:"bytes,10,opt,name=payment_form,json=paymentForm,proto3" json:"payment_form,omitempty"`
	MembershipType          string                 `protobuf:"bytes,11,opt,name=membership_type,json=membershipType,proto3" json:"membership_type,omitempty"`
	RevenueModel            string                 `protobuf:"bytes,12,opt,name=revenue_model,json=revenueModel,proto3" json:"revenue_model,omitempty"`
	HasOnlineEarning        bool                   `protobuf:"varint,13,opt,name=has_online_earning,json=hasOnlineEarning,proto3" json:"has_online_earning,omitempty"`
	MaxRechargeTier         string                 `protobuf:"bytes,14,opt,name=max_recharge_tier,json=maxRechargeTier,proto3" json:"max_recharge_tier,omitempty"`
	MinRechargeTier         string                 `protobuf:"bytes,15,opt,name=min_recharge_tier,json=minRechargeTier,proto3" json:"min_recharge_tier,omitempty"`
	RecommendedRechargeTier string                 `protobuf:"bytes,16,opt,name=recommended_recharge_tier,json=recommendedRechargeTier,proto3" json:"recommended_recharge_tier,omitempty"`
	PropName                string                 `protobuf:"bytes,17,opt,name=prop_name,json=propName,proto3" json:"prop_name,omitempty"`
	MinPaymentTierRange     string                 `protobuf:"bytes,18,opt,name=min_payment_tier_range,json=minPaymentTierRange,proto3" json:"min_payment_tier_range,omitempty"`
	MidPaymentTierRange     string                 `protobuf:"bytes,19,opt,name=mid_payment_tier_range,json=midPaymentTierRange,proto3" json:"mid_payment_tier_range,omitempty"`
	MaxPaymentTierRange     string                 `protobuf:"bytes,20,opt,name=max_payment_tier_range,json=maxPaymentTierRange,proto3" json:"max_payment_tier_range,omitempty"`
	HasDiscount             bool                   `protobuf:"varint,21,opt,name=has_discount,json=hasDiscount,proto3" json:"has_discount,omitempty"`
	DiscountRate            int64                  `protobuf:"varint,22,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MicroAppListItem) Reset() {
	*x = MicroAppListItem{}
	mi := &file_tools_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppListItem) ProtoMessage() {}

func (x *MicroAppListItem) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppListItem.ProtoReflect.Descriptor instead.
func (*MicroAppListItem) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{11}
}

func (x *MicroAppListItem) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *MicroAppListItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *MicroAppListItem) GetAuditStatus() string {
	if x != nil {
		return x.AuditStatus
	}
	return ""
}

func (x *MicroAppListItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MicroAppListItem) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *MicroAppListItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MicroAppListItem) GetModifyTime() string {
	if x != nil {
		return x.ModifyTime
	}
	return ""
}

func (x *MicroAppListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MicroAppListItem) GetTagInfo() string {
	if x != nil {
		return x.TagInfo
	}
	return ""
}

func (x *MicroAppListItem) GetPaymentForm() string {
	if x != nil {
		return x.PaymentForm
	}
	return ""
}

func (x *MicroAppListItem) GetMembershipType() string {
	if x != nil {
		return x.MembershipType
	}
	return ""
}

func (x *MicroAppListItem) GetRevenueModel() string {
	if x != nil {
		return x.RevenueModel
	}
	return ""
}

func (x *MicroAppListItem) GetHasOnlineEarning() bool {
	if x != nil {
		return x.HasOnlineEarning
	}
	return false
}

func (x *MicroAppListItem) GetMaxRechargeTier() string {
	if x != nil {
		return x.MaxRechargeTier
	}
	return ""
}

func (x *MicroAppListItem) GetMinRechargeTier() string {
	if x != nil {
		return x.MinRechargeTier
	}
	return ""
}

func (x *MicroAppListItem) GetRecommendedRechargeTier() string {
	if x != nil {
		return x.RecommendedRechargeTier
	}
	return ""
}

func (x *MicroAppListItem) GetPropName() string {
	if x != nil {
		return x.PropName
	}
	return ""
}

func (x *MicroAppListItem) GetMinPaymentTierRange() string {
	if x != nil {
		return x.MinPaymentTierRange
	}
	return ""
}

func (x *MicroAppListItem) GetMidPaymentTierRange() string {
	if x != nil {
		return x.MidPaymentTierRange
	}
	return ""
}

func (x *MicroAppListItem) GetMaxPaymentTierRange() string {
	if x != nil {
		return x.MaxPaymentTierRange
	}
	return ""
}

func (x *MicroAppListItem) GetHasDiscount() bool {
	if x != nil {
		return x.HasDiscount
	}
	return false
}

func (x *MicroAppListItem) GetDiscountRate() int64 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

type MicroAppDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          *Conf                  `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Params        *MicroAppDetailParams  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailReq) Reset() {
	*x = MicroAppDetailReq{}
	mi := &file_tools_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailReq) ProtoMessage() {}

func (x *MicroAppDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailReq.ProtoReflect.Descriptor instead.
func (*MicroAppDetailReq) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{12}
}

func (x *MicroAppDetailReq) GetConf() *Conf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *MicroAppDetailReq) GetParams() *MicroAppDetailParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type MicroAppDetailParams struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	AdvertiserId  int64                          `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Filtering     *MicroAppDetailParamsFiltering `protobuf:"bytes,2,opt,name=filtering,proto3" json:"filtering,omitempty"`
	Page          int32                          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                          `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailParams) Reset() {
	*x = MicroAppDetailParams{}
	mi := &file_tools_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailParams) ProtoMessage() {}

func (x *MicroAppDetailParams) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailParams.ProtoReflect.Descriptor instead.
func (*MicroAppDetailParams) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{13}
}

func (x *MicroAppDetailParams) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *MicroAppDetailParams) GetFiltering() *MicroAppDetailParamsFiltering {
	if x != nil {
		return x.Filtering
	}
	return nil
}

func (x *MicroAppDetailParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MicroAppDetailParams) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MicroAppDetailParamsFiltering struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	InstanceId    int64                              `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CreateTime    *MicroAppDetailParamsFilteringTime `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailParamsFiltering) Reset() {
	*x = MicroAppDetailParamsFiltering{}
	mi := &file_tools_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailParamsFiltering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailParamsFiltering) ProtoMessage() {}

func (x *MicroAppDetailParamsFiltering) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailParamsFiltering.ProtoReflect.Descriptor instead.
func (*MicroAppDetailParamsFiltering) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{14}
}

func (x *MicroAppDetailParamsFiltering) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *MicroAppDetailParamsFiltering) GetCreateTime() *MicroAppDetailParamsFilteringTime {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type MicroAppDetailParamsFilteringTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailParamsFilteringTime) Reset() {
	*x = MicroAppDetailParamsFilteringTime{}
	mi := &file_tools_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailParamsFilteringTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailParamsFilteringTime) ProtoMessage() {}

func (x *MicroAppDetailParamsFilteringTime) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailParamsFilteringTime.ProtoReflect.Descriptor instead.
func (*MicroAppDetailParamsFilteringTime) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{15}
}

func (x *MicroAppDetailParamsFilteringTime) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MicroAppDetailParamsFilteringTime) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type MicroAppDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *MicroAppDetailData    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailResp) Reset() {
	*x = MicroAppDetailResp{}
	mi := &file_tools_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailResp) ProtoMessage() {}

func (x *MicroAppDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailResp.ProtoReflect.Descriptor instead.
func (*MicroAppDetailResp) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{16}
}

func (x *MicroAppDetailResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MicroAppDetailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MicroAppDetailResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MicroAppDetailResp) GetData() *MicroAppDetailData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MicroAppDetailData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MicroAppDetailItem  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailData) Reset() {
	*x = MicroAppDetailData{}
	mi := &file_tools_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailData) ProtoMessage() {}

func (x *MicroAppDetailData) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailData.ProtoReflect.Descriptor instead.
func (*MicroAppDetailData) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{17}
}

func (x *MicroAppDetailData) GetList() []*MicroAppDetailItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MicroAppDetailData) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type MicroAppDetailItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        int64                  `protobuf:"varint,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AdvertiserId  int64                  `protobuf:"varint,3,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	LinkRemark    string                 `protobuf:"bytes,6,opt,name=link_remark,json=linkRemark,proto3" json:"link_remark,omitempty"`
	StartPage     string                 `protobuf:"bytes,7,opt,name=start_page,json=startPage,proto3" json:"start_page,omitempty"`
	StartParam    string                 `protobuf:"bytes,8,opt,name=start_param,json=startParam,proto3" json:"start_param,omitempty"`
	CreateTime    string                 `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime    string                 `protobuf:"bytes,10,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroAppDetailItem) Reset() {
	*x = MicroAppDetailItem{}
	mi := &file_tools_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroAppDetailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroAppDetailItem) ProtoMessage() {}

func (x *MicroAppDetailItem) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroAppDetailItem.ProtoReflect.Descriptor instead.
func (*MicroAppDetailItem) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{18}
}

func (x *MicroAppDetailItem) GetLinkId() int64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

func (x *MicroAppDetailItem) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *MicroAppDetailItem) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *MicroAppDetailItem) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MicroAppDetailItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *MicroAppDetailItem) GetLinkRemark() string {
	if x != nil {
		return x.LinkRemark
	}
	return ""
}

func (x *MicroAppDetailItem) GetStartPage() string {
	if x != nil {
		return x.StartPage
	}
	return ""
}

func (x *MicroAppDetailItem) GetStartParam() string {
	if x != nil {
		return x.StartParam
	}
	return ""
}

func (x *MicroAppDetailItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MicroAppDetailItem) GetModifyTime() string {
	if x != nil {
		return x.ModifyTime
	}
	return ""
}

var File_tools_proto protoreflect.FileDescriptor

const file_tools_proto_rawDesc = "" +
	"\n" +
	"\vtools.proto\x12\x05ocean\x1a\n" +
	"conf.proto\"z\n" +
	"\x10SharedAdvertiser\x120\n" +
	"\x14shared_advertiser_id\x18\x01 \x01(\x03R\x12sharedAdvertiserId\x124\n" +
	"\x16shared_advertiser_name\x18\x02 \x01(\tR\x14sharedAdvertiserName\"\x91\x04\n" +
	"\n" +
	"AwemesData\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x04R\fadvertiserId\x12'\n" +
	"\x0fadvertiser_name\x18\x02 \x01(\tR\x0eadvertiserName\x12\x15\n" +
	"\x06ies_id\x18\x03 \x01(\x04R\x05iesId\x12\"\n" +
	"\ries_user_name\x18\x04 \x01(\tR\viesUserName\x12\x19\n" +
	"\baweme_id\x18\x05 \x01(\tR\aawemeId\x12\x1d\n" +
	"\n" +
	"aweme_name\x18\x06 \x01(\tR\tawemeName\x12!\n" +
	"\faweme_avatar\x18\a \x01(\tR\vawemeAvatar\x12\x1b\n" +
	"\tbind_type\x18\b \x01(\tR\bbindType\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1b\n" +
	"\tleft_days\x18\n" +
	" \x01(\x05R\bleftDays\x12\x1d\n" +
	"\n" +
	"start_time\x18\v \x01(\tR\tstartTime\x124\n" +
	"\x16shared_advertiser_name\x18\f \x01(\tR\x14sharedAdvertiserName\x12.\n" +
	"\x13commerce_user_level\x18\r \x01(\tR\x11commerceUserLevel\x12F\n" +
	"\x12shared_advertisers\x18\x0e \x03(\v2\x17.ocean.SharedAdvertiserR\x11sharedAdvertisers\"[\n" +
	"\tAwemesReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x12.\n" +
	"\x06params\x18\x02 \x01(\v2\x16.ocean.AwemesReqParamsR\x06params\"6\n" +
	"\x0fAwemesReqParams\x12#\n" +
	"\radvertiser_id\x18\x02 \x01(\x04R\fadvertiserId\"\x80\x01\n" +
	"\n" +
	"AwemesResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12%\n" +
	"\x04data\x18\x05 \x03(\v2\x11.ocean.AwemesDataR\x04data\"d\n" +
	"\x0fMicroAppListReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x121\n" +
	"\x06params\x18\x02 \x01(\v2\x19.ocean.MicroAppListParamsR\x06params\"\xac\x01\n" +
	"\x12MicroAppListParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x03R\fadvertiserId\x12@\n" +
	"\tfiltering\x18\x02 \x01(\v2\".ocean.MicroAppListParamsFilteringR\tfiltering\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xc9\x01\n" +
	"\x1bMicroAppListParamsFiltering\x12\x1d\n" +
	"\n" +
	"search_key\x18\x01 \x01(\tR\tsearchKey\x12!\n" +
	"\faudit_status\x18\x02 \x01(\tR\vauditStatus\x12\x1f\n" +
	"\vsearch_type\x18\x03 \x01(\tR\n" +
	"searchType\x12G\n" +
	"\vcreate_time\x18\x04 \x01(\v2&.ocean.MicroAppListParamsFilteringTimeR\n" +
	"createTime\"[\n" +
	"\x1fMicroAppListParamsFilteringTime\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\"\x8c\x01\n" +
	"\x10MicroAppListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.ocean.MicroAppListDataR\x04data\"l\n" +
	"\x10MicroAppListData\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.ocean.MicroAppListItemR\x04list\x12+\n" +
	"\tpage_info\x18\x02 \x01(\v2\x0e.conf.PageInfoR\bpageInfo\"\xd3\x06\n" +
	"\x10MicroAppListItem\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x12!\n" +
	"\faudit_status\x18\x03 \x01(\tR\vauditStatus\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12#\n" +
	"\radvertiser_id\x18\x05 \x01(\x03R\fadvertiserId\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vmodify_time\x18\a \x01(\tR\n" +
	"modifyTime\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x19\n" +
	"\btag_info\x18\t \x01(\tR\atagInfo\x12!\n" +
	"\fpayment_form\x18\n" +
	" \x01(\tR\vpaymentForm\x12'\n" +
	"\x0fmembership_type\x18\v \x01(\tR\x0emembershipType\x12#\n" +
	"\rrevenue_model\x18\f \x01(\tR\frevenueModel\x12,\n" +
	"\x12has_online_earning\x18\r \x01(\bR\x10hasOnlineEarning\x12*\n" +
	"\x11max_recharge_tier\x18\x0e \x01(\tR\x0fmaxRechargeTier\x12*\n" +
	"\x11min_recharge_tier\x18\x0f \x01(\tR\x0fminRechargeTier\x12:\n" +
	"\x19recommended_recharge_tier\x18\x10 \x01(\tR\x17recommendedRechargeTier\x12\x1b\n" +
	"\tprop_name\x18\x11 \x01(\tR\bpropName\x123\n" +
	"\x16min_payment_tier_range\x18\x12 \x01(\tR\x13minPaymentTierRange\x123\n" +
	"\x16mid_payment_tier_range\x18\x13 \x01(\tR\x13midPaymentTierRange\x123\n" +
	"\x16max_payment_tier_range\x18\x14 \x01(\tR\x13maxPaymentTierRange\x12!\n" +
	"\fhas_discount\x18\x15 \x01(\bR\vhasDiscount\x12#\n" +
	"\rdiscount_rate\x18\x16 \x01(\x03R\fdiscountRate\"h\n" +
	"\x11MicroAppDetailReq\x12\x1e\n" +
	"\x04conf\x18\x01 \x01(\v2\n" +
	".conf.ConfR\x04conf\x123\n" +
	"\x06params\x18\x02 \x01(\v2\x1b.ocean.MicroAppDetailParamsR\x06params\"\xb0\x01\n" +
	"\x14MicroAppDetailParams\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\x03R\fadvertiserId\x12B\n" +
	"\tfiltering\x18\x02 \x01(\v2$.ocean.MicroAppDetailParamsFilteringR\tfiltering\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8b\x01\n" +
	"\x1dMicroAppDetailParamsFiltering\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12I\n" +
	"\vcreate_time\x18\x02 \x01(\v2(.ocean.MicroAppDetailParamsFilteringTimeR\n" +
	"createTime\"]\n" +
	"!MicroAppDetailParamsFilteringTime\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\"\x90\x01\n" +
	"\x12MicroAppDetailResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12-\n" +
	"\x04data\x18\x04 \x01(\v2\x19.ocean.MicroAppDetailDataR\x04data\"p\n" +
	"\x12MicroAppDetailData\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.ocean.MicroAppDetailItemR\x04list\x12+\n" +
	"\tpage_info\x18\x02 \x01(\v2\x0e.conf.PageInfoR\bpageInfo\"\xc1\x02\n" +
	"\x12MicroAppDetailItem\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\x03R\x06linkId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12#\n" +
	"\radvertiser_id\x18\x03 \x01(\x03R\fadvertiserId\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x1f\n" +
	"\vlink_remark\x18\x06 \x01(\tR\n" +
	"linkRemark\x12\x1d\n" +
	"\n" +
	"start_page\x18\a \x01(\tR\tstartPage\x12\x1f\n" +
	"\vstart_param\x18\b \x01(\tR\n" +
	"startParam\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vmodify_time\x18\n" +
	" \x01(\tR\n" +
	"modifyTimeB-Z+github.com/nbzhu/ad-api-gateway-proto;protob\x06proto3"

var (
	file_tools_proto_rawDescOnce sync.Once
	file_tools_proto_rawDescData []byte
)

func file_tools_proto_rawDescGZIP() []byte {
	file_tools_proto_rawDescOnce.Do(func() {
		file_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)))
	})
	return file_tools_proto_rawDescData
}

var file_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_tools_proto_goTypes = []any{
	(*SharedAdvertiser)(nil),                  // 0: ocean.SharedAdvertiser
	(*AwemesData)(nil),                        // 1: ocean.AwemesData
	(*AwemesReq)(nil),                         // 2: ocean.AwemesReq
	(*AwemesReqParams)(nil),                   // 3: ocean.AwemesReqParams
	(*AwemesResp)(nil),                        // 4: ocean.AwemesResp
	(*MicroAppListReq)(nil),                   // 5: ocean.MicroAppListReq
	(*MicroAppListParams)(nil),                // 6: ocean.MicroAppListParams
	(*MicroAppListParamsFiltering)(nil),       // 7: ocean.MicroAppListParamsFiltering
	(*MicroAppListParamsFilteringTime)(nil),   // 8: ocean.MicroAppListParamsFilteringTime
	(*MicroAppListResp)(nil),                  // 9: ocean.MicroAppListResp
	(*MicroAppListData)(nil),                  // 10: ocean.MicroAppListData
	(*MicroAppListItem)(nil),                  // 11: ocean.MicroAppListItem
	(*MicroAppDetailReq)(nil),                 // 12: ocean.MicroAppDetailReq
	(*MicroAppDetailParams)(nil),              // 13: ocean.MicroAppDetailParams
	(*MicroAppDetailParamsFiltering)(nil),     // 14: ocean.MicroAppDetailParamsFiltering
	(*MicroAppDetailParamsFilteringTime)(nil), // 15: ocean.MicroAppDetailParamsFilteringTime
	(*MicroAppDetailResp)(nil),                // 16: ocean.MicroAppDetailResp
	(*MicroAppDetailData)(nil),                // 17: ocean.MicroAppDetailData
	(*MicroAppDetailItem)(nil),                // 18: ocean.MicroAppDetailItem
	(*Conf)(nil),                              // 19: conf.Conf
	(*PageInfo)(nil),                          // 20: conf.PageInfo
}
var file_tools_proto_depIdxs = []int32{
	0,  // 0: ocean.AwemesData.shared_advertisers:type_name -> ocean.SharedAdvertiser
	19, // 1: ocean.AwemesReq.conf:type_name -> conf.Conf
	3,  // 2: ocean.AwemesReq.params:type_name -> ocean.AwemesReqParams
	1,  // 3: ocean.AwemesResp.data:type_name -> ocean.AwemesData
	19, // 4: ocean.MicroAppListReq.conf:type_name -> conf.Conf
	6,  // 5: ocean.MicroAppListReq.params:type_name -> ocean.MicroAppListParams
	7,  // 6: ocean.MicroAppListParams.filtering:type_name -> ocean.MicroAppListParamsFiltering
	8,  // 7: ocean.MicroAppListParamsFiltering.create_time:type_name -> ocean.MicroAppListParamsFilteringTime
	10, // 8: ocean.MicroAppListResp.data:type_name -> ocean.MicroAppListData
	11, // 9: ocean.MicroAppListData.list:type_name -> ocean.MicroAppListItem
	20, // 10: ocean.MicroAppListData.page_info:type_name -> conf.PageInfo
	19, // 11: ocean.MicroAppDetailReq.conf:type_name -> conf.Conf
	13, // 12: ocean.MicroAppDetailReq.params:type_name -> ocean.MicroAppDetailParams
	14, // 13: ocean.MicroAppDetailParams.filtering:type_name -> ocean.MicroAppDetailParamsFiltering
	15, // 14: ocean.MicroAppDetailParamsFiltering.create_time:type_name -> ocean.MicroAppDetailParamsFilteringTime
	17, // 15: ocean.MicroAppDetailResp.data:type_name -> ocean.MicroAppDetailData
	18, // 16: ocean.MicroAppDetailData.list:type_name -> ocean.MicroAppDetailItem
	20, // 17: ocean.MicroAppDetailData.page_info:type_name -> conf.PageInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_tools_proto_init() }
func file_tools_proto_init() {
	if File_tools_proto != nil {
		return
	}
	file_conf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tools_proto_goTypes,
		DependencyIndexes: file_tools_proto_depIdxs,
		MessageInfos:      file_tools_proto_msgTypes,
	}.Build()
	File_tools_proto = out.File
	file_tools_proto_goTypes = nil
	file_tools_proto_depIdxs = nil
}
